version: '3.5'

services:
  api:
    image: dqtoan0123/plane_server:latest
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - '3009:3000'
    volumes:
      - .:/server
      - /server/node_modules
  web:
    image: dqtoan0123/plane_web:latest
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/web
      - /web/node_modules
  
