GET https://api.plane.so/api/workspaces/vlxx2/projects/?is_favorite=all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzAwMzkxMzE4LCJpYXQiOjE2OTk3ODY1MTgsImp0aSI6ImI1NWNiM2UyZWE4YjRiMWJhZTVmOTMyZTVmNTRlMTI5IiwidXNlcl9pZCI6ImE1NzM4ZjhkLTA5OWItNDgwMS04YTllLTljMjE1YTg2NTZlZiJ9.rVKxdmY5AdhuN45XvLLBZzVJsrprPpRZRvR3neDAUhk