GET https://api.plane.so/api/workspaces/vcl/projects/2404df9a-adac-4107-9af6-93eb7754a82d/states/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzAxMDc1NTQ1LCJpYXQiOjE3MDA0NzA3NDUsImp0aSI6ImRkNjQzZjQ2YzE2MTRmOTM4MTNmODIxZmQ1ODA5MTNlIiwidXNlcl9pZCI6ImE1NzM4ZjhkLTA5OWItNDgwMS04YTllLTljMjE1YTg2NTZlZiJ9.-Z2iMKMK4CfSawZUSZA1MqJVkJjv2mlhKlnW6CD5F0g