package com.server.plane.mapper;

import com.server.plane.entity.AnalyticViews;
import com.server.plane.entity.AnalyticViewsExample;
import com.server.plane.entity.AnalyticViewsWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AnalyticViewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analytic_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    long countByExample(AnalyticViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analytic_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByExample(AnalyticViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analytic_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analytic_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insert(AnalyticViewsWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analytic_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insertSelective(AnalyticViewsWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analytic_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<AnalyticViewsWithBLOBs> selectByExampleWithBLOBs(AnalyticViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analytic_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<AnalyticViews> selectByExample(AnalyticViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analytic_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    AnalyticViewsWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analytic_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleSelective(@Param("row") AnalyticViewsWithBLOBs row, @Param("example") AnalyticViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analytic_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleWithBLOBs(@Param("row") AnalyticViewsWithBLOBs row, @Param("example") AnalyticViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analytic_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExample(@Param("row") AnalyticViews row, @Param("example") AnalyticViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analytic_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeySelective(AnalyticViewsWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analytic_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeyWithBLOBs(AnalyticViewsWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table analytic_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKey(AnalyticViews row);
}