package com.server.plane.mapper;

import com.server.plane.entity.CycleUserProperties;
import com.server.plane.entity.CycleUserPropertiesExample;
import com.server.plane.entity.CycleUserPropertiesWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CycleUserPropertiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_user_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    long countByExample(CycleUserPropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_user_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByExample(CycleUserPropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_user_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_user_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insert(CycleUserPropertiesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_user_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insertSelective(CycleUserPropertiesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_user_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<CycleUserPropertiesWithBLOBs> selectByExampleWithBLOBs(CycleUserPropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_user_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<CycleUserProperties> selectByExample(CycleUserPropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_user_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    CycleUserPropertiesWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_user_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleSelective(@Param("row") CycleUserPropertiesWithBLOBs row, @Param("example") CycleUserPropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_user_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleWithBLOBs(@Param("row") CycleUserPropertiesWithBLOBs row, @Param("example") CycleUserPropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_user_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExample(@Param("row") CycleUserProperties row, @Param("example") CycleUserPropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_user_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeySelective(CycleUserPropertiesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_user_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeyWithBLOBs(CycleUserPropertiesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_user_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKey(CycleUserProperties row);
}