package com.server.plane.mapper;

import com.server.plane.entity.CycleFavorites;
import com.server.plane.entity.CycleFavoritesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CycleFavoritesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    long countByExample(CycleFavoritesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByExample(CycleFavoritesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insert(CycleFavorites row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insertSelective(CycleFavorites row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<CycleFavorites> selectByExample(CycleFavoritesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    CycleFavorites selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleSelective(@Param("row") CycleFavorites row, @Param("example") CycleFavoritesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExample(@Param("row") CycleFavorites row, @Param("example") CycleFavoritesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeySelective(CycleFavorites row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycle_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKey(CycleFavorites row);
}