package com.server.plane.mapper;

import com.server.plane.entity.Cycles;
import com.server.plane.entity.CyclesExample;
import com.server.plane.entity.CyclesWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CyclesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycles
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    long countByExample(CyclesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycles
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByExample(CyclesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycles
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycles
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insert(CyclesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycles
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insertSelective(CyclesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycles
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<CyclesWithBLOBs> selectByExampleWithBLOBs(CyclesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycles
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<Cycles> selectByExample(CyclesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycles
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    CyclesWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycles
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleSelective(@Param("row") CyclesWithBLOBs row, @Param("example") CyclesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycles
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleWithBLOBs(@Param("row") CyclesWithBLOBs row, @Param("example") CyclesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycles
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExample(@Param("row") Cycles row, @Param("example") CyclesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycles
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeySelective(CyclesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycles
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeyWithBLOBs(CyclesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cycles
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKey(Cycles row);
}