package com.server.plane.mapper;

import com.server.plane.entity.EstimatePoints;
import com.server.plane.entity.EstimatePointsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EstimatePointsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimate_points
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    long countByExample(EstimatePointsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimate_points
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByExample(EstimatePointsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimate_points
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimate_points
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insert(EstimatePoints row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimate_points
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insertSelective(EstimatePoints row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimate_points
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<EstimatePoints> selectByExampleWithBLOBs(EstimatePointsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimate_points
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<EstimatePoints> selectByExample(EstimatePointsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimate_points
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    EstimatePoints selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimate_points
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleSelective(@Param("row") EstimatePoints row, @Param("example") EstimatePointsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimate_points
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleWithBLOBs(@Param("row") EstimatePoints row, @Param("example") EstimatePointsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimate_points
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExample(@Param("row") EstimatePoints row, @Param("example") EstimatePointsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimate_points
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeySelective(EstimatePoints row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimate_points
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeyWithBLOBs(EstimatePoints row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table estimate_points
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKey(EstimatePoints row);
}