package com.server.plane.mapper;

import com.server.plane.entity.ExporterHistories;
import com.server.plane.entity.ExporterHistoriesExample;
import com.server.plane.entity.ExporterHistoriesWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExporterHistoriesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exporter_histories
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    long countByExample(ExporterHistoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exporter_histories
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByExample(ExporterHistoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exporter_histories
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exporter_histories
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insert(ExporterHistoriesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exporter_histories
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insertSelective(ExporterHistoriesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exporter_histories
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<ExporterHistoriesWithBLOBs> selectByExampleWithBLOBs(ExporterHistoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exporter_histories
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<ExporterHistories> selectByExample(ExporterHistoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exporter_histories
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    ExporterHistoriesWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exporter_histories
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleSelective(@Param("row") ExporterHistoriesWithBLOBs row, @Param("example") ExporterHistoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exporter_histories
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleWithBLOBs(@Param("row") ExporterHistoriesWithBLOBs row, @Param("example") ExporterHistoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exporter_histories
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExample(@Param("row") ExporterHistories row, @Param("example") ExporterHistoriesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exporter_histories
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeySelective(ExporterHistoriesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exporter_histories
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeyWithBLOBs(ExporterHistoriesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exporter_histories
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKey(ExporterHistories row);
}