package com.server.plane.mapper;

import com.server.plane.entity.FileAssets;
import com.server.plane.entity.FileAssetsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FileAssetsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_assets
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    long countByExample(FileAssetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_assets
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByExample(FileAssetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_assets
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_assets
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insert(FileAssets row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_assets
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insertSelective(FileAssets row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_assets
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<FileAssets> selectByExampleWithBLOBs(FileAssetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_assets
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<FileAssets> selectByExample(FileAssetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_assets
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    FileAssets selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_assets
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleSelective(@Param("row") FileAssets row, @Param("example") FileAssetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_assets
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleWithBLOBs(@Param("row") FileAssets row, @Param("example") FileAssetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_assets
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExample(@Param("row") FileAssets row, @Param("example") FileAssetsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_assets
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeySelective(FileAssets row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_assets
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeyWithBLOBs(FileAssets row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_assets
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKey(FileAssets row);
}