package com.server.plane.mapper;

import com.server.plane.entity.GlobalViews;
import com.server.plane.entity.GlobalViewsExample;
import com.server.plane.entity.GlobalViewsWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GlobalViewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    long countByExample(GlobalViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByExample(GlobalViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insert(GlobalViewsWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insertSelective(GlobalViewsWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<GlobalViewsWithBLOBs> selectByExampleWithBLOBs(GlobalViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<GlobalViews> selectByExample(GlobalViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    GlobalViewsWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleSelective(@Param("row") GlobalViewsWithBLOBs row, @Param("example") GlobalViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleWithBLOBs(@Param("row") GlobalViewsWithBLOBs row, @Param("example") GlobalViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExample(@Param("row") GlobalViews row, @Param("example") GlobalViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeySelective(GlobalViewsWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeyWithBLOBs(GlobalViewsWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKey(GlobalViews row);
}