package com.server.plane.mapper;

import com.server.plane.entity.Importers;
import com.server.plane.entity.ImportersExample;
import com.server.plane.entity.ImportersWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ImportersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importers
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    long countByExample(ImportersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importers
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByExample(ImportersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importers
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importers
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insert(ImportersWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importers
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insertSelective(ImportersWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importers
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<ImportersWithBLOBs> selectByExampleWithBLOBs(ImportersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importers
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<Importers> selectByExample(ImportersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importers
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    ImportersWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importers
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleSelective(@Param("row") ImportersWithBLOBs row, @Param("example") ImportersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importers
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleWithBLOBs(@Param("row") ImportersWithBLOBs row, @Param("example") ImportersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importers
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExample(@Param("row") Importers row, @Param("example") ImportersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importers
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeySelective(ImportersWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importers
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeyWithBLOBs(ImportersWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table importers
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKey(Importers row);
}