package com.server.plane.mapper;

import com.server.plane.entity.Inboxes;
import com.server.plane.entity.InboxesExample;
import com.server.plane.entity.InboxesWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InboxesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inboxes
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    long countByExample(InboxesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inboxes
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByExample(InboxesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inboxes
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inboxes
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insert(InboxesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inboxes
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insertSelective(InboxesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inboxes
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<InboxesWithBLOBs> selectByExampleWithBLOBs(InboxesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inboxes
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<Inboxes> selectByExample(InboxesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inboxes
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    InboxesWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inboxes
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleSelective(@Param("row") InboxesWithBLOBs row, @Param("example") InboxesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inboxes
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleWithBLOBs(@Param("row") InboxesWithBLOBs row, @Param("example") InboxesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inboxes
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExample(@Param("row") Inboxes row, @Param("example") InboxesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inboxes
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeySelective(InboxesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inboxes
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeyWithBLOBs(InboxesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inboxes
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKey(Inboxes row);
}