package com.server.plane.mapper;

import com.server.plane.entity.IssueLinks;
import com.server.plane.entity.IssueLinksExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IssueLinksMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_links
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    long countByExample(IssueLinksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_links
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByExample(IssueLinksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_links
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_links
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insert(IssueLinks row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_links
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insertSelective(IssueLinks row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_links
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<IssueLinks> selectByExampleWithBLOBs(IssueLinksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_links
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<IssueLinks> selectByExample(IssueLinksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_links
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    IssueLinks selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_links
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleSelective(@Param("row") IssueLinks row, @Param("example") IssueLinksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_links
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleWithBLOBs(@Param("row") IssueLinks row, @Param("example") IssueLinksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_links
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExample(@Param("row") IssueLinks row, @Param("example") IssueLinksExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_links
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeySelective(IssueLinks row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_links
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeyWithBLOBs(IssueLinks row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_links
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKey(IssueLinks row);
}