package com.server.plane.mapper;

import com.server.plane.entity.IssueProperties;
import com.server.plane.entity.IssuePropertiesExample;
import com.server.plane.entity.IssuePropertiesWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IssuePropertiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    long countByExample(IssuePropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByExample(IssuePropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insert(IssuePropertiesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insertSelective(IssuePropertiesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<IssuePropertiesWithBLOBs> selectByExampleWithBLOBs(IssuePropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<IssueProperties> selectByExample(IssuePropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    IssuePropertiesWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleSelective(@Param("row") IssuePropertiesWithBLOBs row, @Param("example") IssuePropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleWithBLOBs(@Param("row") IssuePropertiesWithBLOBs row, @Param("example") IssuePropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExample(@Param("row") IssueProperties row, @Param("example") IssuePropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeySelective(IssuePropertiesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeyWithBLOBs(IssuePropertiesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKey(IssueProperties row);
}