package com.server.plane.mapper;

import com.server.plane.entity.IssueViews;
import com.server.plane.entity.IssueViewsExample;
import com.server.plane.entity.IssueViewsWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IssueViewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    long countByExample(IssueViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByExample(IssueViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insert(IssueViewsWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insertSelective(IssueViewsWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<IssueViewsWithBLOBs> selectByExampleWithBLOBs(IssueViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<IssueViews> selectByExample(IssueViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    IssueViewsWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleSelective(@Param("row") IssueViewsWithBLOBs row, @Param("example") IssueViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleWithBLOBs(@Param("row") IssueViewsWithBLOBs row, @Param("example") IssueViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExample(@Param("row") IssueViews row, @Param("example") IssueViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeySelective(IssueViewsWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeyWithBLOBs(IssueViewsWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKey(IssueViews row);
}