package com.server.plane.mapper;

import com.server.plane.entity.IssueSequences;
import com.server.plane.entity.IssueSequencesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IssueSequencesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_sequences
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    long countByExample(IssueSequencesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_sequences
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByExample(IssueSequencesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_sequences
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_sequences
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insert(IssueSequences row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_sequences
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insertSelective(IssueSequences row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_sequences
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<IssueSequences> selectByExample(IssueSequencesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_sequences
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    IssueSequences selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_sequences
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleSelective(@Param("row") IssueSequences row, @Param("example") IssueSequencesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_sequences
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExample(@Param("row") IssueSequences row, @Param("example") IssueSequencesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_sequences
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeySelective(IssueSequences row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_sequences
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKey(IssueSequences row);
}