package com.server.plane.mapper;

import com.server.plane.entity.IssueLabel;
import com.server.plane.entity.IssueLabelExample;
import com.server.plane.entity.IssueLabelKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IssueLabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_label
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    long countByExample(IssueLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_label
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByExample(IssueLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_label
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByPrimaryKey(IssueLabelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_label
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insert(IssueLabel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_label
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insertSelective(IssueLabel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_label
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<IssueLabel> selectByExample(IssueLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_label
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    IssueLabel selectByPrimaryKey(IssueLabelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_label
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleSelective(@Param("row") IssueLabel row, @Param("example") IssueLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_label
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExample(@Param("row") IssueLabel row, @Param("example") IssueLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_label
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeySelective(IssueLabel row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_label
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKey(IssueLabel row);
}