package com.server.plane.mapper;

import com.server.plane.entity.IssueAssignees;
import com.server.plane.entity.IssueAssigneesExample;
import com.server.plane.entity.IssueAssigneesKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IssueAssigneesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_assignees
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    long countByExample(IssueAssigneesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_assignees
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByExample(IssueAssigneesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_assignees
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByPrimaryKey(IssueAssigneesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_assignees
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insert(IssueAssignees row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_assignees
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insertSelective(IssueAssignees row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_assignees
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<IssueAssignees> selectByExample(IssueAssigneesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_assignees
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    IssueAssignees selectByPrimaryKey(IssueAssigneesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_assignees
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleSelective(@Param("row") IssueAssignees row, @Param("example") IssueAssigneesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_assignees
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExample(@Param("row") IssueAssignees row, @Param("example") IssueAssigneesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_assignees
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeySelective(IssueAssignees row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table issue_assignees
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKey(IssueAssignees row);
}