package com.server.plane.mapper;

import com.server.plane.entity.Modules;
import com.server.plane.entity.ModulesExample;
import com.server.plane.entity.ModulesWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ModulesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modules
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    long countByExample(ModulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modules
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByExample(ModulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modules
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modules
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insert(ModulesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modules
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insertSelective(ModulesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modules
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<ModulesWithBLOBs> selectByExampleWithBLOBs(ModulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modules
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<Modules> selectByExample(ModulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modules
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    ModulesWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modules
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleSelective(@Param("row") ModulesWithBLOBs row, @Param("example") ModulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modules
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleWithBLOBs(@Param("row") ModulesWithBLOBs row, @Param("example") ModulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modules
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExample(@Param("row") Modules row, @Param("example") ModulesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modules
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeySelective(ModulesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modules
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeyWithBLOBs(ModulesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modules
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKey(Modules row);
}