package com.server.plane.mapper;

import com.server.plane.entity.ModuleFavorites;
import com.server.plane.entity.ModuleFavoritesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ModuleFavoritesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    long countByExample(ModuleFavoritesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByExample(ModuleFavoritesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insert(ModuleFavorites row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insertSelective(ModuleFavorites row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<ModuleFavorites> selectByExample(ModuleFavoritesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    ModuleFavorites selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleSelective(@Param("row") ModuleFavorites row, @Param("example") ModuleFavoritesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExample(@Param("row") ModuleFavorites row, @Param("example") ModuleFavoritesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeySelective(ModuleFavorites row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKey(ModuleFavorites row);
}