package com.server.plane.mapper;

import com.server.plane.entity.ModuleUserProperties;
import com.server.plane.entity.ModuleUserPropertiesExample;
import com.server.plane.entity.ModuleUserPropertiesWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ModuleUserPropertiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_user_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    long countByExample(ModuleUserPropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_user_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByExample(ModuleUserPropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_user_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_user_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insert(ModuleUserPropertiesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_user_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insertSelective(ModuleUserPropertiesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_user_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<ModuleUserPropertiesWithBLOBs> selectByExampleWithBLOBs(ModuleUserPropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_user_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<ModuleUserProperties> selectByExample(ModuleUserPropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_user_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    ModuleUserPropertiesWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_user_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleSelective(@Param("row") ModuleUserPropertiesWithBLOBs row, @Param("example") ModuleUserPropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_user_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleWithBLOBs(@Param("row") ModuleUserPropertiesWithBLOBs row, @Param("example") ModuleUserPropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_user_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExample(@Param("row") ModuleUserProperties row, @Param("example") ModuleUserPropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_user_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeySelective(ModuleUserPropertiesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_user_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeyWithBLOBs(ModuleUserPropertiesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_user_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKey(ModuleUserProperties row);
}