package com.server.plane.mapper;

import com.server.plane.entity.ModuleMembers;
import com.server.plane.entity.ModuleMembersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ModuleMembersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    long countByExample(ModuleMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByExample(ModuleMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insert(ModuleMembers row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insertSelective(ModuleMembers row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<ModuleMembers> selectByExample(ModuleMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    ModuleMembers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleSelective(@Param("row") ModuleMembers row, @Param("example") ModuleMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExample(@Param("row") ModuleMembers row, @Param("example") ModuleMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeySelective(ModuleMembers row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table module_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKey(ModuleMembers row);
}