package com.server.plane.mapper;

import com.server.plane.entity.PageLabels;
import com.server.plane.entity.PageLabelsExample;
import com.server.plane.entity.PageLabelsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PageLabelsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_labels
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    long countByExample(PageLabelsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_labels
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByExample(PageLabelsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_labels
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByPrimaryKey(PageLabelsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_labels
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insert(PageLabels row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_labels
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insertSelective(PageLabels row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_labels
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<PageLabels> selectByExample(PageLabelsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_labels
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    PageLabels selectByPrimaryKey(PageLabelsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_labels
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleSelective(@Param("row") PageLabels row, @Param("example") PageLabelsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_labels
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExample(@Param("row") PageLabels row, @Param("example") PageLabelsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_labels
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeySelective(PageLabels row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_labels
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKey(PageLabels row);
}