package com.server.plane.mapper;

import com.server.plane.entity.Pages;
import com.server.plane.entity.PagesExample;
import com.server.plane.entity.PagesWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pages
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    long countByExample(PagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pages
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByExample(PagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pages
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pages
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insert(PagesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pages
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insertSelective(PagesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pages
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<PagesWithBLOBs> selectByExampleWithBLOBs(PagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pages
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<Pages> selectByExample(PagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pages
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    PagesWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pages
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleSelective(@Param("row") PagesWithBLOBs row, @Param("example") PagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pages
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleWithBLOBs(@Param("row") PagesWithBLOBs row, @Param("example") PagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pages
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExample(@Param("row") Pages row, @Param("example") PagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pages
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeySelective(PagesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pages
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeyWithBLOBs(PagesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pages
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKey(Pages row);
}