package com.server.plane.mapper;

import com.server.plane.entity.ProjectIdentifiers;
import com.server.plane.entity.ProjectIdentifiersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProjectIdentifiersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_identifiers
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    long countByExample(ProjectIdentifiersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_identifiers
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByExample(ProjectIdentifiersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_identifiers
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_identifiers
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insert(ProjectIdentifiers row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_identifiers
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insertSelective(ProjectIdentifiers row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_identifiers
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<ProjectIdentifiers> selectByExample(ProjectIdentifiersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_identifiers
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    ProjectIdentifiers selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_identifiers
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleSelective(@Param("row") ProjectIdentifiers row, @Param("example") ProjectIdentifiersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_identifiers
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExample(@Param("row") ProjectIdentifiers row, @Param("example") ProjectIdentifiersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_identifiers
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeySelective(ProjectIdentifiers row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_identifiers
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKey(ProjectIdentifiers row);
}