package com.server.plane.mapper;

import com.server.plane.entity.ProjectFavorites;
import com.server.plane.entity.ProjectFavoritesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProjectFavoritesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    long countByExample(ProjectFavoritesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByExample(ProjectFavoritesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insert(ProjectFavorites row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insertSelective(ProjectFavorites row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<ProjectFavorites> selectByExample(ProjectFavoritesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    ProjectFavorites selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleSelective(@Param("row") ProjectFavorites row, @Param("example") ProjectFavoritesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExample(@Param("row") ProjectFavorites row, @Param("example") ProjectFavoritesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeySelective(ProjectFavorites row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_favorites
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKey(ProjectFavorites row);
}