package com.server.plane.mapper;

import com.server.plane.entity.ProjectMembers;
import com.server.plane.entity.ProjectMembersExample;
import com.server.plane.entity.ProjectMembersWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProjectMembersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    long countByExample(ProjectMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByExample(ProjectMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insert(ProjectMembersWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insertSelective(ProjectMembersWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<ProjectMembersWithBLOBs> selectByExampleWithBLOBs(ProjectMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<ProjectMembers> selectByExample(ProjectMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    ProjectMembersWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleSelective(@Param("row") ProjectMembersWithBLOBs row, @Param("example") ProjectMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleWithBLOBs(@Param("row") ProjectMembersWithBLOBs row, @Param("example") ProjectMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExample(@Param("row") ProjectMembers row, @Param("example") ProjectMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeySelective(ProjectMembersWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeyWithBLOBs(ProjectMembersWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKey(ProjectMembers row);
}