package com.server.plane.mapper;

import com.server.plane.entity.ProjectViews;
import com.server.plane.entity.ProjectViewsExample;
import com.server.plane.entity.ProjectViewsWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProjectViewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    long countByExample(ProjectViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByExample(ProjectViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insert(ProjectViewsWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insertSelective(ProjectViewsWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<ProjectViewsWithBLOBs> selectByExampleWithBLOBs(ProjectViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<ProjectViews> selectByExample(ProjectViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    ProjectViewsWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleSelective(@Param("row") ProjectViewsWithBLOBs row, @Param("example") ProjectViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleWithBLOBs(@Param("row") ProjectViewsWithBLOBs row, @Param("example") ProjectViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExample(@Param("row") ProjectViews row, @Param("example") ProjectViewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeySelective(ProjectViewsWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeyWithBLOBs(ProjectViewsWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_views
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKey(ProjectViews row);
}