package com.server.plane.mapper;

import com.server.plane.entity.SocialLoginConnections;
import com.server.plane.entity.SocialLoginConnectionsExample;
import com.server.plane.entity.SocialLoginConnectionsWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SocialLoginConnectionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table social_login_connections
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    long countByExample(SocialLoginConnectionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table social_login_connections
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByExample(SocialLoginConnectionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table social_login_connections
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table social_login_connections
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insert(SocialLoginConnectionsWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table social_login_connections
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insertSelective(SocialLoginConnectionsWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table social_login_connections
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<SocialLoginConnectionsWithBLOBs> selectByExampleWithBLOBs(SocialLoginConnectionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table social_login_connections
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<SocialLoginConnections> selectByExample(SocialLoginConnectionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table social_login_connections
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    SocialLoginConnectionsWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table social_login_connections
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleSelective(@Param("row") SocialLoginConnectionsWithBLOBs row, @Param("example") SocialLoginConnectionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table social_login_connections
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleWithBLOBs(@Param("row") SocialLoginConnectionsWithBLOBs row, @Param("example") SocialLoginConnectionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table social_login_connections
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExample(@Param("row") SocialLoginConnections row, @Param("example") SocialLoginConnectionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table social_login_connections
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeySelective(SocialLoginConnectionsWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table social_login_connections
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeyWithBLOBs(SocialLoginConnectionsWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table social_login_connections
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKey(SocialLoginConnections row);
}