package com.server.plane.mapper;

import com.server.plane.entity.TeamMembers;
import com.server.plane.entity.TeamMembersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeamMembersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    long countByExample(TeamMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByExample(TeamMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insert(TeamMembers row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insertSelective(TeamMembers row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<TeamMembers> selectByExample(TeamMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    TeamMembers selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleSelective(@Param("row") TeamMembers row, @Param("example") TeamMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExample(@Param("row") TeamMembers row, @Param("example") TeamMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeySelective(TeamMembers row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table team_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKey(TeamMembers row);
}