package com.server.plane.mapper;

import com.server.plane.entity.Workspaces;
import com.server.plane.entity.WorkspacesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WorkspacesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspaces
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    long countByExample(WorkspacesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspaces
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByExample(WorkspacesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspaces
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspaces
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insert(Workspaces row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspaces
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insertSelective(Workspaces row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspaces
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<Workspaces> selectByExample(WorkspacesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspaces
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    Workspaces selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspaces
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleSelective(@Param("row") Workspaces row, @Param("example") WorkspacesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspaces
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExample(@Param("row") Workspaces row, @Param("example") WorkspacesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspaces
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeySelective(Workspaces row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspaces
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKey(Workspaces row);
}