package com.server.plane.mapper;

import com.server.plane.entity.WorkspaceThemes;
import com.server.plane.entity.WorkspaceThemesExample;
import com.server.plane.entity.WorkspaceThemesWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WorkspaceThemesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace_themes
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    long countByExample(WorkspaceThemesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace_themes
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByExample(WorkspaceThemesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace_themes
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace_themes
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insert(WorkspaceThemesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace_themes
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insertSelective(WorkspaceThemesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace_themes
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<WorkspaceThemesWithBLOBs> selectByExampleWithBLOBs(WorkspaceThemesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace_themes
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<WorkspaceThemes> selectByExample(WorkspaceThemesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace_themes
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    WorkspaceThemesWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace_themes
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleSelective(@Param("row") WorkspaceThemesWithBLOBs row, @Param("example") WorkspaceThemesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace_themes
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleWithBLOBs(@Param("row") WorkspaceThemesWithBLOBs row, @Param("example") WorkspaceThemesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace_themes
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExample(@Param("row") WorkspaceThemes row, @Param("example") WorkspaceThemesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace_themes
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeySelective(WorkspaceThemesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace_themes
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeyWithBLOBs(WorkspaceThemesWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace_themes
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKey(WorkspaceThemes row);
}