package com.server.plane.mapper;

import com.server.plane.entity.WorkspaceMembers;
import com.server.plane.entity.WorkspaceMembersExample;
import com.server.plane.entity.WorkspaceMembersWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WorkspaceMembersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    long countByExample(WorkspaceMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByExample(WorkspaceMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insert(WorkspaceMembersWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int insertSelective(WorkspaceMembersWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<WorkspaceMembersWithBLOBs> selectByExampleWithBLOBs(WorkspaceMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    List<WorkspaceMembers> selectByExample(WorkspaceMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    WorkspaceMembersWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleSelective(@Param("row") WorkspaceMembersWithBLOBs row, @Param("example") WorkspaceMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExampleWithBLOBs(@Param("row") WorkspaceMembersWithBLOBs row, @Param("example") WorkspaceMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByExample(@Param("row") WorkspaceMembers row, @Param("example") WorkspaceMembersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeySelective(WorkspaceMembersWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKeyWithBLOBs(WorkspaceMembersWithBLOBs row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workspace_members
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    int updateByPrimaryKey(WorkspaceMembers row);
}