import { TApiKey } from './type';

function getKeySWR(key: string) {
  return (id: TApiKey) => id ? id + key : null;
}

export const SWR_KEY_MEMBER_BY_WORKSPACE = 'API_SWR_KEY_MEMBER_BY_PROJECT';

export const SWR_KEY_ISSUE_VIEWS = 'SWR_KEY_ISSUE_VIEWS';

export const SWR_KEY_PROJECTS = getKeySWR('SWR_KEY_PROJECTS')

export const SWR_KEY_ISSUES_BY_PROJECT_ID = getKeySWR('SWR_KEY_ISSUES_BY_PROJECT_ID')

export const SWR_KEY_STATES = getKeySWR('SWR_KEY_STATES')

export const SWR_KEY_STATES_PROJECT = getKeySWR('SWR_KEY_STATES_PROJECT')

export const SWR_KEY_MEMBER_BY_PROJECT = getKeySWR('SWR_KEY_MEMBER_BY_PROJECT')

export const SWR_KEY_ISSUE_VIEW = getKeySWR('SWR_KEY_ISSUE_VIEW')

export const SWR_KEY_LABELS_BY_PROJECT = getKeySWR('SWR_KEY_LABELS_BY_PROJECT')

export const SWR_KEY_CYCLES_BY_PROJECT = getKeySWR('SWR_KEY_CYCLES_BY_PROJECT')

export const SWR_KEY_MODULES_BY_PROJECT = getKeySWR('SWR_KEY_MODULES_BY_PROJECT')

export const SWR_KEY_PROJECT_VIEW = getKeySWR('SWR_KEY_PROJECT_VIEW')

export const SWR_KEY_PROJECT_VIEW_DETAIL = getKeySWR('SWR_KEY_PROJECT_VIEW_DETAIL')

export const SWR_KEY_PROJECT_PAGE = getKeySWR('SWR_KEY_PROJECT_PAGE')

export const SWR_KEY_LS_ISSUE_REACTIONS = getKeySWR('SWR_KEY_LS_ISSUE_REACTIONS')

export const SWR_KEY_LS_ISSUE_LINK = getKeySWR('SWR_KEY_LS_ISSUE_LINK')

export const SWR_KEY_ESTIMATES = getKeySWR('SWR_KEY_ESTIMATES')
