package com.server.plane.entity;

public class AnalyticViewsWithBLOBs extends AnalyticViews {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analytic_views.description
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analytic_views.query
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String query;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analytic_views.query_dict
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String queryDict;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analytic_views.description
     *
     * @return the value of analytic_views.description
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analytic_views.description
     *
     * @param description the value for analytic_views.description
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analytic_views.query
     *
     * @return the value of analytic_views.query
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getQuery() {
        return query;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analytic_views.query
     *
     * @param query the value for analytic_views.query
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setQuery(String query) {
        this.query = query == null ? null : query.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analytic_views.query_dict
     *
     * @return the value of analytic_views.query_dict
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getQueryDict() {
        return queryDict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analytic_views.query_dict
     *
     * @param queryDict the value for analytic_views.query_dict
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setQueryDict(String queryDict) {
        this.queryDict = queryDict == null ? null : queryDict.trim();
    }
}