package com.server.plane.entity;

import java.util.Date;

public class AnalyticViews {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analytic_views.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analytic_views.workspace_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String workspaceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analytic_views.name
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analytic_views.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column analytic_views.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analytic_views.id
     *
     * @return the value of analytic_views.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analytic_views.id
     *
     * @param id the value for analytic_views.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analytic_views.workspace_id
     *
     * @return the value of analytic_views.workspace_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getWorkspaceId() {
        return workspaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analytic_views.workspace_id
     *
     * @param workspaceId the value for analytic_views.workspace_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId == null ? null : workspaceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analytic_views.name
     *
     * @return the value of analytic_views.name
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analytic_views.name
     *
     * @param name the value for analytic_views.name
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analytic_views.created_at
     *
     * @return the value of analytic_views.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analytic_views.created_at
     *
     * @param createdAt the value for analytic_views.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column analytic_views.updated_at
     *
     * @return the value of analytic_views.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column analytic_views.updated_at
     *
     * @param updatedAt the value for analytic_views.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}