package com.server.plane.entity;

import java.util.Date;

public class CommentReaction {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_reaction.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_reaction.actor
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String actor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_reaction.comment
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_reaction.reaction
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String reaction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_reaction.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_reaction.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_reaction.id
     *
     * @return the value of comment_reaction.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_reaction.id
     *
     * @param id the value for comment_reaction.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_reaction.actor
     *
     * @return the value of comment_reaction.actor
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getActor() {
        return actor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_reaction.actor
     *
     * @param actor the value for comment_reaction.actor
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setActor(String actor) {
        this.actor = actor == null ? null : actor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_reaction.comment
     *
     * @return the value of comment_reaction.comment
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_reaction.comment
     *
     * @param comment the value for comment_reaction.comment
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_reaction.reaction
     *
     * @return the value of comment_reaction.reaction
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getReaction() {
        return reaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_reaction.reaction
     *
     * @param reaction the value for comment_reaction.reaction
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setReaction(String reaction) {
        this.reaction = reaction == null ? null : reaction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_reaction.created_at
     *
     * @return the value of comment_reaction.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_reaction.created_at
     *
     * @param createdAt the value for comment_reaction.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_reaction.updated_at
     *
     * @return the value of comment_reaction.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_reaction.updated_at
     *
     * @param updatedAt the value for comment_reaction.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}