package com.server.plane.entity;

public class CyclesWithBLOBs extends Cycles {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycles.description
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycles.view_props
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String viewProps;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycles.description
     *
     * @return the value of cycles.description
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycles.description
     *
     * @param description the value for cycles.description
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycles.view_props
     *
     * @return the value of cycles.view_props
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getViewProps() {
        return viewProps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycles.view_props
     *
     * @param viewProps the value for cycles.view_props
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setViewProps(String viewProps) {
        this.viewProps = viewProps == null ? null : viewProps.trim();
    }
}