package com.server.plane.entity;

import java.util.Date;

public class Cycles {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycles.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycles.owned_by
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String ownedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycles.created_by
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycles.project_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycles.workspace_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String workspaceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycles.name
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycles.start_date
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycles.end_date
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycles.sort_order
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Float sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycles.createdAt
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date createdat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cycles.updatedAt
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date updatedat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycles.id
     *
     * @return the value of cycles.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycles.id
     *
     * @param id the value for cycles.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycles.owned_by
     *
     * @return the value of cycles.owned_by
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getOwnedBy() {
        return ownedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycles.owned_by
     *
     * @param ownedBy the value for cycles.owned_by
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setOwnedBy(String ownedBy) {
        this.ownedBy = ownedBy == null ? null : ownedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycles.created_by
     *
     * @return the value of cycles.created_by
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycles.created_by
     *
     * @param createdBy the value for cycles.created_by
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycles.project_id
     *
     * @return the value of cycles.project_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycles.project_id
     *
     * @param projectId the value for cycles.project_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycles.workspace_id
     *
     * @return the value of cycles.workspace_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getWorkspaceId() {
        return workspaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycles.workspace_id
     *
     * @param workspaceId the value for cycles.workspace_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId == null ? null : workspaceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycles.name
     *
     * @return the value of cycles.name
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycles.name
     *
     * @param name the value for cycles.name
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycles.start_date
     *
     * @return the value of cycles.start_date
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycles.start_date
     *
     * @param startDate the value for cycles.start_date
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycles.end_date
     *
     * @return the value of cycles.end_date
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycles.end_date
     *
     * @param endDate the value for cycles.end_date
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycles.sort_order
     *
     * @return the value of cycles.sort_order
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Float getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycles.sort_order
     *
     * @param sortOrder the value for cycles.sort_order
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setSortOrder(Float sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycles.createdAt
     *
     * @return the value of cycles.createdAt
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycles.createdAt
     *
     * @param createdat the value for cycles.createdAt
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cycles.updatedAt
     *
     * @return the value of cycles.updatedAt
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getUpdatedat() {
        return updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cycles.updatedAt
     *
     * @param updatedat the value for cycles.updatedAt
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setUpdatedat(Date updatedat) {
        this.updatedat = updatedat;
    }
}