package com.server.plane.entity;

import java.util.Date;

public class EstimatePoints {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estimate_points.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estimate_points.estimate_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String estimateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estimate_points.key
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Integer key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estimate_points.value
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estimate_points.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estimate_points.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column estimate_points.description
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estimate_points.id
     *
     * @return the value of estimate_points.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estimate_points.id
     *
     * @param id the value for estimate_points.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estimate_points.estimate_id
     *
     * @return the value of estimate_points.estimate_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getEstimateId() {
        return estimateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estimate_points.estimate_id
     *
     * @param estimateId the value for estimate_points.estimate_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setEstimateId(String estimateId) {
        this.estimateId = estimateId == null ? null : estimateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estimate_points.key
     *
     * @return the value of estimate_points.key
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Integer getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estimate_points.key
     *
     * @param key the value for estimate_points.key
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setKey(Integer key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estimate_points.value
     *
     * @return the value of estimate_points.value
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estimate_points.value
     *
     * @param value the value for estimate_points.value
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estimate_points.created_at
     *
     * @return the value of estimate_points.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estimate_points.created_at
     *
     * @param createdAt the value for estimate_points.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estimate_points.updated_at
     *
     * @return the value of estimate_points.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estimate_points.updated_at
     *
     * @param updatedAt the value for estimate_points.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column estimate_points.description
     *
     * @return the value of estimate_points.description
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column estimate_points.description
     *
     * @param description the value for estimate_points.description
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}