package com.server.plane.entity;

public class ImportersWithBLOBs extends Importers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importers.metadata
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String metadata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importers.config
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String config;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importers.data
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String data;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importers.imported_data
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String importedData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importers.metadata
     *
     * @return the value of importers.metadata
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getMetadata() {
        return metadata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importers.metadata
     *
     * @param metadata the value for importers.metadata
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setMetadata(String metadata) {
        this.metadata = metadata == null ? null : metadata.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importers.config
     *
     * @return the value of importers.config
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getConfig() {
        return config;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importers.config
     *
     * @param config the value for importers.config
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setConfig(String config) {
        this.config = config == null ? null : config.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importers.data
     *
     * @return the value of importers.data
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importers.data
     *
     * @param data the value for importers.data
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importers.imported_data
     *
     * @return the value of importers.imported_data
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getImportedData() {
        return importedData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importers.imported_data
     *
     * @param importedData the value for importers.imported_data
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setImportedData(String importedData) {
        this.importedData = importedData == null ? null : importedData.trim();
    }
}