package com.server.plane.entity;

import java.util.Date;

public class Importers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importers.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importers.token
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importers.initiated_by
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String initiatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importers.service
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String service;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importers.status
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importers.createdAt
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date createdat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column importers.updatedAt
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date updatedat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importers.id
     *
     * @return the value of importers.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importers.id
     *
     * @param id the value for importers.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importers.token
     *
     * @return the value of importers.token
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importers.token
     *
     * @param token the value for importers.token
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importers.initiated_by
     *
     * @return the value of importers.initiated_by
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getInitiatedBy() {
        return initiatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importers.initiated_by
     *
     * @param initiatedBy the value for importers.initiated_by
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setInitiatedBy(String initiatedBy) {
        this.initiatedBy = initiatedBy == null ? null : initiatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importers.service
     *
     * @return the value of importers.service
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getService() {
        return service;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importers.service
     *
     * @param service the value for importers.service
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setService(String service) {
        this.service = service == null ? null : service.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importers.status
     *
     * @return the value of importers.status
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importers.status
     *
     * @param status the value for importers.status
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importers.createdAt
     *
     * @return the value of importers.createdAt
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importers.createdAt
     *
     * @param createdat the value for importers.createdAt
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column importers.updatedAt
     *
     * @return the value of importers.updatedAt
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getUpdatedat() {
        return updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column importers.updatedAt
     *
     * @param updatedat the value for importers.updatedAt
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setUpdatedat(Date updatedat) {
        this.updatedat = updatedat;
    }
}