package com.server.plane.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class InboxIssuesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inbox_issues
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inbox_issues
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inbox_issues
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox_issues
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public InboxIssuesExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox_issues
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox_issues
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox_issues
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox_issues
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox_issues
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox_issues
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox_issues
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox_issues
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox_issues
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox_issues
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inbox_issues
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIssueIdIsNull() {
            addCriterion("issue_id is null");
            return (Criteria) this;
        }

        public Criteria andIssueIdIsNotNull() {
            addCriterion("issue_id is not null");
            return (Criteria) this;
        }

        public Criteria andIssueIdEqualTo(String value) {
            addCriterion("issue_id =", value, "issueId");
            return (Criteria) this;
        }

        public Criteria andIssueIdNotEqualTo(String value) {
            addCriterion("issue_id <>", value, "issueId");
            return (Criteria) this;
        }

        public Criteria andIssueIdGreaterThan(String value) {
            addCriterion("issue_id >", value, "issueId");
            return (Criteria) this;
        }

        public Criteria andIssueIdGreaterThanOrEqualTo(String value) {
            addCriterion("issue_id >=", value, "issueId");
            return (Criteria) this;
        }

        public Criteria andIssueIdLessThan(String value) {
            addCriterion("issue_id <", value, "issueId");
            return (Criteria) this;
        }

        public Criteria andIssueIdLessThanOrEqualTo(String value) {
            addCriterion("issue_id <=", value, "issueId");
            return (Criteria) this;
        }

        public Criteria andIssueIdLike(String value) {
            addCriterion("issue_id like", value, "issueId");
            return (Criteria) this;
        }

        public Criteria andIssueIdNotLike(String value) {
            addCriterion("issue_id not like", value, "issueId");
            return (Criteria) this;
        }

        public Criteria andIssueIdIn(List<String> values) {
            addCriterion("issue_id in", values, "issueId");
            return (Criteria) this;
        }

        public Criteria andIssueIdNotIn(List<String> values) {
            addCriterion("issue_id not in", values, "issueId");
            return (Criteria) this;
        }

        public Criteria andIssueIdBetween(String value1, String value2) {
            addCriterion("issue_id between", value1, value2, "issueId");
            return (Criteria) this;
        }

        public Criteria andIssueIdNotBetween(String value1, String value2) {
            addCriterion("issue_id not between", value1, value2, "issueId");
            return (Criteria) this;
        }

        public Criteria andInboxIdIsNull() {
            addCriterion("inbox_id is null");
            return (Criteria) this;
        }

        public Criteria andInboxIdIsNotNull() {
            addCriterion("inbox_id is not null");
            return (Criteria) this;
        }

        public Criteria andInboxIdEqualTo(String value) {
            addCriterion("inbox_id =", value, "inboxId");
            return (Criteria) this;
        }

        public Criteria andInboxIdNotEqualTo(String value) {
            addCriterion("inbox_id <>", value, "inboxId");
            return (Criteria) this;
        }

        public Criteria andInboxIdGreaterThan(String value) {
            addCriterion("inbox_id >", value, "inboxId");
            return (Criteria) this;
        }

        public Criteria andInboxIdGreaterThanOrEqualTo(String value) {
            addCriterion("inbox_id >=", value, "inboxId");
            return (Criteria) this;
        }

        public Criteria andInboxIdLessThan(String value) {
            addCriterion("inbox_id <", value, "inboxId");
            return (Criteria) this;
        }

        public Criteria andInboxIdLessThanOrEqualTo(String value) {
            addCriterion("inbox_id <=", value, "inboxId");
            return (Criteria) this;
        }

        public Criteria andInboxIdLike(String value) {
            addCriterion("inbox_id like", value, "inboxId");
            return (Criteria) this;
        }

        public Criteria andInboxIdNotLike(String value) {
            addCriterion("inbox_id not like", value, "inboxId");
            return (Criteria) this;
        }

        public Criteria andInboxIdIn(List<String> values) {
            addCriterion("inbox_id in", values, "inboxId");
            return (Criteria) this;
        }

        public Criteria andInboxIdNotIn(List<String> values) {
            addCriterion("inbox_id not in", values, "inboxId");
            return (Criteria) this;
        }

        public Criteria andInboxIdBetween(String value1, String value2) {
            addCriterion("inbox_id between", value1, value2, "inboxId");
            return (Criteria) this;
        }

        public Criteria andInboxIdNotBetween(String value1, String value2) {
            addCriterion("inbox_id not between", value1, value2, "inboxId");
            return (Criteria) this;
        }

        public Criteria andIdIssueDuplicateToIsNull() {
            addCriterion("id_issue_duplicate_to is null");
            return (Criteria) this;
        }

        public Criteria andIdIssueDuplicateToIsNotNull() {
            addCriterion("id_issue_duplicate_to is not null");
            return (Criteria) this;
        }

        public Criteria andIdIssueDuplicateToEqualTo(String value) {
            addCriterion("id_issue_duplicate_to =", value, "idIssueDuplicateTo");
            return (Criteria) this;
        }

        public Criteria andIdIssueDuplicateToNotEqualTo(String value) {
            addCriterion("id_issue_duplicate_to <>", value, "idIssueDuplicateTo");
            return (Criteria) this;
        }

        public Criteria andIdIssueDuplicateToGreaterThan(String value) {
            addCriterion("id_issue_duplicate_to >", value, "idIssueDuplicateTo");
            return (Criteria) this;
        }

        public Criteria andIdIssueDuplicateToGreaterThanOrEqualTo(String value) {
            addCriterion("id_issue_duplicate_to >=", value, "idIssueDuplicateTo");
            return (Criteria) this;
        }

        public Criteria andIdIssueDuplicateToLessThan(String value) {
            addCriterion("id_issue_duplicate_to <", value, "idIssueDuplicateTo");
            return (Criteria) this;
        }

        public Criteria andIdIssueDuplicateToLessThanOrEqualTo(String value) {
            addCriterion("id_issue_duplicate_to <=", value, "idIssueDuplicateTo");
            return (Criteria) this;
        }

        public Criteria andIdIssueDuplicateToLike(String value) {
            addCriterion("id_issue_duplicate_to like", value, "idIssueDuplicateTo");
            return (Criteria) this;
        }

        public Criteria andIdIssueDuplicateToNotLike(String value) {
            addCriterion("id_issue_duplicate_to not like", value, "idIssueDuplicateTo");
            return (Criteria) this;
        }

        public Criteria andIdIssueDuplicateToIn(List<String> values) {
            addCriterion("id_issue_duplicate_to in", values, "idIssueDuplicateTo");
            return (Criteria) this;
        }

        public Criteria andIdIssueDuplicateToNotIn(List<String> values) {
            addCriterion("id_issue_duplicate_to not in", values, "idIssueDuplicateTo");
            return (Criteria) this;
        }

        public Criteria andIdIssueDuplicateToBetween(String value1, String value2) {
            addCriterion("id_issue_duplicate_to between", value1, value2, "idIssueDuplicateTo");
            return (Criteria) this;
        }

        public Criteria andIdIssueDuplicateToNotBetween(String value1, String value2) {
            addCriterion("id_issue_duplicate_to not between", value1, value2, "idIssueDuplicateTo");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("\"status\" is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("\"status\" is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("\"status\" =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("\"status\" <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("\"status\" >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"status\" >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("\"status\" <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("\"status\" <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("\"status\" in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("\"status\" not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("\"status\" between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("\"status\" not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andSnoozedTillIsNull() {
            addCriterion("snoozed_till is null");
            return (Criteria) this;
        }

        public Criteria andSnoozedTillIsNotNull() {
            addCriterion("snoozed_till is not null");
            return (Criteria) this;
        }

        public Criteria andSnoozedTillEqualTo(Date value) {
            addCriterion("snoozed_till =", value, "snoozedTill");
            return (Criteria) this;
        }

        public Criteria andSnoozedTillNotEqualTo(Date value) {
            addCriterion("snoozed_till <>", value, "snoozedTill");
            return (Criteria) this;
        }

        public Criteria andSnoozedTillGreaterThan(Date value) {
            addCriterion("snoozed_till >", value, "snoozedTill");
            return (Criteria) this;
        }

        public Criteria andSnoozedTillGreaterThanOrEqualTo(Date value) {
            addCriterion("snoozed_till >=", value, "snoozedTill");
            return (Criteria) this;
        }

        public Criteria andSnoozedTillLessThan(Date value) {
            addCriterion("snoozed_till <", value, "snoozedTill");
            return (Criteria) this;
        }

        public Criteria andSnoozedTillLessThanOrEqualTo(Date value) {
            addCriterion("snoozed_till <=", value, "snoozedTill");
            return (Criteria) this;
        }

        public Criteria andSnoozedTillIn(List<Date> values) {
            addCriterion("snoozed_till in", values, "snoozedTill");
            return (Criteria) this;
        }

        public Criteria andSnoozedTillNotIn(List<Date> values) {
            addCriterion("snoozed_till not in", values, "snoozedTill");
            return (Criteria) this;
        }

        public Criteria andSnoozedTillBetween(Date value1, Date value2) {
            addCriterion("snoozed_till between", value1, value2, "snoozedTill");
            return (Criteria) this;
        }

        public Criteria andSnoozedTillNotBetween(Date value1, Date value2) {
            addCriterion("snoozed_till not between", value1, value2, "snoozedTill");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inbox_issues
     *
     * @mbg.generated do_not_delete_during_merge Tue Dec 23 23:56:04 ICT 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table inbox_issues
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}