package com.server.plane.entity;

public class IssueLabelKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_label.issue_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String issueId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_label.label_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String labelId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_label.issue_id
     *
     * @return the value of issue_label.issue_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getIssueId() {
        return issueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_label.issue_id
     *
     * @param issueId the value for issue_label.issue_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setIssueId(String issueId) {
        this.issueId = issueId == null ? null : issueId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_label.label_id
     *
     * @return the value of issue_label.label_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_label.label_id
     *
     * @param labelId the value for issue_label.label_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setLabelId(String labelId) {
        this.labelId = labelId == null ? null : labelId.trim();
    }
}