package com.server.plane.entity;

import java.util.Date;

public class IssueSubscribers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_subscribers.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_subscribers.issue_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String issueId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_subscribers.subscriber
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String subscriber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_subscribers.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_subscribers.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_subscribers.id
     *
     * @return the value of issue_subscribers.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_subscribers.id
     *
     * @param id the value for issue_subscribers.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_subscribers.issue_id
     *
     * @return the value of issue_subscribers.issue_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getIssueId() {
        return issueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_subscribers.issue_id
     *
     * @param issueId the value for issue_subscribers.issue_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setIssueId(String issueId) {
        this.issueId = issueId == null ? null : issueId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_subscribers.subscriber
     *
     * @return the value of issue_subscribers.subscriber
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getSubscriber() {
        return subscriber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_subscribers.subscriber
     *
     * @param subscriber the value for issue_subscribers.subscriber
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setSubscriber(String subscriber) {
        this.subscriber = subscriber == null ? null : subscriber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_subscribers.created_at
     *
     * @return the value of issue_subscribers.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_subscribers.created_at
     *
     * @param createdAt the value for issue_subscribers.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_subscribers.updated_at
     *
     * @return the value of issue_subscribers.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_subscribers.updated_at
     *
     * @param updatedAt the value for issue_subscribers.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}