package com.server.plane.entity;

public class IssueAssigneesKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_assignees.issue_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String issueId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_assignees.assignee
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String assignee;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_assignees.issue_id
     *
     * @return the value of issue_assignees.issue_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getIssueId() {
        return issueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_assignees.issue_id
     *
     * @param issueId the value for issue_assignees.issue_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setIssueId(String issueId) {
        this.issueId = issueId == null ? null : issueId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_assignees.assignee
     *
     * @return the value of issue_assignees.assignee
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getAssignee() {
        return assignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_assignees.assignee
     *
     * @param assignee the value for issue_assignees.assignee
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setAssignee(String assignee) {
        this.assignee = assignee == null ? null : assignee.trim();
    }
}