package com.server.plane.entity;

import java.util.Date;

public class IssueBlockers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_blockers.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_blockers.block
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String block;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_blockers.blocked_by
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String blockedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_blockers.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_blockers.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_blockers.blocked_bys
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String blockedBys;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_blockers.blocks
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String blocks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_blockers.id
     *
     * @return the value of issue_blockers.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_blockers.id
     *
     * @param id the value for issue_blockers.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_blockers.block
     *
     * @return the value of issue_blockers.block
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getBlock() {
        return block;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_blockers.block
     *
     * @param block the value for issue_blockers.block
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setBlock(String block) {
        this.block = block == null ? null : block.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_blockers.blocked_by
     *
     * @return the value of issue_blockers.blocked_by
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getBlockedBy() {
        return blockedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_blockers.blocked_by
     *
     * @param blockedBy the value for issue_blockers.blocked_by
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setBlockedBy(String blockedBy) {
        this.blockedBy = blockedBy == null ? null : blockedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_blockers.created_at
     *
     * @return the value of issue_blockers.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_blockers.created_at
     *
     * @param createdAt the value for issue_blockers.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_blockers.updated_at
     *
     * @return the value of issue_blockers.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_blockers.updated_at
     *
     * @param updatedAt the value for issue_blockers.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_blockers.blocked_bys
     *
     * @return the value of issue_blockers.blocked_bys
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getBlockedBys() {
        return blockedBys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_blockers.blocked_bys
     *
     * @param blockedBys the value for issue_blockers.blocked_bys
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setBlockedBys(String blockedBys) {
        this.blockedBys = blockedBys == null ? null : blockedBys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_blockers.blocks
     *
     * @return the value of issue_blockers.blocks
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getBlocks() {
        return blocks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_blockers.blocks
     *
     * @param blocks the value for issue_blockers.blocks
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setBlocks(String blocks) {
        this.blocks = blocks == null ? null : blocks.trim();
    }
}