package com.server.plane.entity;

public class IssueViewsWithBLOBs extends IssueViews {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_views.query
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String query;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue_views.query_data
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String queryData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_views.query
     *
     * @return the value of issue_views.query
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getQuery() {
        return query;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_views.query
     *
     * @param query the value for issue_views.query
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setQuery(String query) {
        this.query = query == null ? null : query.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue_views.query_data
     *
     * @return the value of issue_views.query_data
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getQueryData() {
        return queryData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue_views.query_data
     *
     * @param queryData the value for issue_views.query_data
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setQueryData(String queryData) {
        this.queryData = queryData == null ? null : queryData.trim();
    }
}