package com.server.plane.entity;

import java.util.Date;

public class Issue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue.project_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue.create_by
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue.workspace_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String workspaceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue.parent
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String parent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue.state_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String stateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue.estimate_point_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String estimatePointId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue.name
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue.priority
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue.start_date
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue.target_date
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date targetDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue.sequence_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Integer sequenceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue.sort_order
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Integer sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue.completed_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date completedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue.archived_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date archivedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue.is_draft
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Boolean isDraft;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column issue.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue.id
     *
     * @return the value of issue.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue.id
     *
     * @param id the value for issue.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue.project_id
     *
     * @return the value of issue.project_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue.project_id
     *
     * @param projectId the value for issue.project_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue.create_by
     *
     * @return the value of issue.create_by
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue.create_by
     *
     * @param createBy the value for issue.create_by
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue.workspace_id
     *
     * @return the value of issue.workspace_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getWorkspaceId() {
        return workspaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue.workspace_id
     *
     * @param workspaceId the value for issue.workspace_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId == null ? null : workspaceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue.parent
     *
     * @return the value of issue.parent
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getParent() {
        return parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue.parent
     *
     * @param parent the value for issue.parent
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setParent(String parent) {
        this.parent = parent == null ? null : parent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue.state_id
     *
     * @return the value of issue.state_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getStateId() {
        return stateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue.state_id
     *
     * @param stateId the value for issue.state_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setStateId(String stateId) {
        this.stateId = stateId == null ? null : stateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue.estimate_point_id
     *
     * @return the value of issue.estimate_point_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getEstimatePointId() {
        return estimatePointId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue.estimate_point_id
     *
     * @param estimatePointId the value for issue.estimate_point_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setEstimatePointId(String estimatePointId) {
        this.estimatePointId = estimatePointId == null ? null : estimatePointId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue.name
     *
     * @return the value of issue.name
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue.name
     *
     * @param name the value for issue.name
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue.priority
     *
     * @return the value of issue.priority
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue.priority
     *
     * @param priority the value for issue.priority
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setPriority(String priority) {
        this.priority = priority == null ? null : priority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue.start_date
     *
     * @return the value of issue.start_date
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue.start_date
     *
     * @param startDate the value for issue.start_date
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue.target_date
     *
     * @return the value of issue.target_date
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getTargetDate() {
        return targetDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue.target_date
     *
     * @param targetDate the value for issue.target_date
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setTargetDate(Date targetDate) {
        this.targetDate = targetDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue.sequence_id
     *
     * @return the value of issue.sequence_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Integer getSequenceId() {
        return sequenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue.sequence_id
     *
     * @param sequenceId the value for issue.sequence_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setSequenceId(Integer sequenceId) {
        this.sequenceId = sequenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue.sort_order
     *
     * @return the value of issue.sort_order
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue.sort_order
     *
     * @param sortOrder the value for issue.sort_order
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue.completed_at
     *
     * @return the value of issue.completed_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getCompletedAt() {
        return completedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue.completed_at
     *
     * @param completedAt the value for issue.completed_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setCompletedAt(Date completedAt) {
        this.completedAt = completedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue.archived_at
     *
     * @return the value of issue.archived_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getArchivedAt() {
        return archivedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue.archived_at
     *
     * @param archivedAt the value for issue.archived_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setArchivedAt(Date archivedAt) {
        this.archivedAt = archivedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue.is_draft
     *
     * @return the value of issue.is_draft
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Boolean getIsDraft() {
        return isDraft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue.is_draft
     *
     * @param isDraft the value for issue.is_draft
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setIsDraft(Boolean isDraft) {
        this.isDraft = isDraft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue.created_at
     *
     * @return the value of issue.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue.created_at
     *
     * @param createdAt the value for issue.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column issue.updated_at
     *
     * @return the value of issue.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column issue.updated_at
     *
     * @param updatedAt the value for issue.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}