package com.server.plane.entity;

public class ModuleUserPropertiesWithBLOBs extends ModuleUserProperties {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_user_properties.filters
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String filters;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_user_properties.display_filters
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String displayFilters;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_user_properties.display_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String displayProperties;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_user_properties.filters
     *
     * @return the value of module_user_properties.filters
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getFilters() {
        return filters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_user_properties.filters
     *
     * @param filters the value for module_user_properties.filters
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setFilters(String filters) {
        this.filters = filters == null ? null : filters.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_user_properties.display_filters
     *
     * @return the value of module_user_properties.display_filters
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getDisplayFilters() {
        return displayFilters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_user_properties.display_filters
     *
     * @param displayFilters the value for module_user_properties.display_filters
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setDisplayFilters(String displayFilters) {
        this.displayFilters = displayFilters == null ? null : displayFilters.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_user_properties.display_properties
     *
     * @return the value of module_user_properties.display_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getDisplayProperties() {
        return displayProperties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_user_properties.display_properties
     *
     * @param displayProperties the value for module_user_properties.display_properties
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setDisplayProperties(String displayProperties) {
        this.displayProperties = displayProperties == null ? null : displayProperties.trim();
    }
}