package com.server.plane.entity;

public class ModulesWithBLOBs extends Modules {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modules.description_text
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String descriptionText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modules.description_html
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String descriptionHtml;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modules.view_props
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String viewProps;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modules.description_text
     *
     * @return the value of modules.description_text
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getDescriptionText() {
        return descriptionText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modules.description_text
     *
     * @param descriptionText the value for modules.description_text
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setDescriptionText(String descriptionText) {
        this.descriptionText = descriptionText == null ? null : descriptionText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modules.description_html
     *
     * @return the value of modules.description_html
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getDescriptionHtml() {
        return descriptionHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modules.description_html
     *
     * @param descriptionHtml the value for modules.description_html
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setDescriptionHtml(String descriptionHtml) {
        this.descriptionHtml = descriptionHtml == null ? null : descriptionHtml.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modules.view_props
     *
     * @return the value of modules.view_props
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getViewProps() {
        return viewProps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modules.view_props
     *
     * @param viewProps the value for modules.view_props
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setViewProps(String viewProps) {
        this.viewProps = viewProps == null ? null : viewProps.trim();
    }
}