package com.server.plane.entity;

import java.util.Date;

public class ModuleLinks {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_links.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_links.module_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String moduleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_links.title
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_links.url
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_links.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_links.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_links.metadata
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String metadata;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_links.id
     *
     * @return the value of module_links.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_links.id
     *
     * @param id the value for module_links.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_links.module_id
     *
     * @return the value of module_links.module_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_links.module_id
     *
     * @param moduleId the value for module_links.module_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId == null ? null : moduleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_links.title
     *
     * @return the value of module_links.title
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_links.title
     *
     * @param title the value for module_links.title
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_links.url
     *
     * @return the value of module_links.url
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_links.url
     *
     * @param url the value for module_links.url
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_links.created_at
     *
     * @return the value of module_links.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_links.created_at
     *
     * @param createdAt the value for module_links.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_links.updated_at
     *
     * @return the value of module_links.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_links.updated_at
     *
     * @param updatedAt the value for module_links.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_links.metadata
     *
     * @return the value of module_links.metadata
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getMetadata() {
        return metadata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_links.metadata
     *
     * @param metadata the value for module_links.metadata
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setMetadata(String metadata) {
        this.metadata = metadata == null ? null : metadata.trim();
    }
}