package com.server.plane.entity;

import java.util.Date;

public class ModuleFavorites {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_favorites.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_favorites.user_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_favorites.module_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String moduleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_favorites.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_favorites.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_favorites.id
     *
     * @return the value of module_favorites.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_favorites.id
     *
     * @param id the value for module_favorites.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_favorites.user_id
     *
     * @return the value of module_favorites.user_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_favorites.user_id
     *
     * @param userId the value for module_favorites.user_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_favorites.module_id
     *
     * @return the value of module_favorites.module_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_favorites.module_id
     *
     * @param moduleId the value for module_favorites.module_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId == null ? null : moduleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_favorites.created_at
     *
     * @return the value of module_favorites.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_favorites.created_at
     *
     * @param createdAt the value for module_favorites.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_favorites.updated_at
     *
     * @return the value of module_favorites.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_favorites.updated_at
     *
     * @param updatedAt the value for module_favorites.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}