package com.server.plane.entity;

import java.util.Date;

public class ModuleMembers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_members.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_members.module_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String moduleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_members.member
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String member;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_members.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column module_members.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_members.id
     *
     * @return the value of module_members.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_members.id
     *
     * @param id the value for module_members.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_members.module_id
     *
     * @return the value of module_members.module_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_members.module_id
     *
     * @param moduleId the value for module_members.module_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setModuleId(String moduleId) {
        this.moduleId = moduleId == null ? null : moduleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_members.member
     *
     * @return the value of module_members.member
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getMember() {
        return member;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_members.member
     *
     * @param member the value for module_members.member
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setMember(String member) {
        this.member = member == null ? null : member.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_members.created_at
     *
     * @return the value of module_members.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_members.created_at
     *
     * @param createdAt the value for module_members.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column module_members.updated_at
     *
     * @return the value of module_members.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column module_members.updated_at
     *
     * @param updatedAt the value for module_members.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}