package com.server.plane.entity;

import java.util.Date;

public class Notifications {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.workspace_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String workspaceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.project_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.triggered_by
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String triggeredBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.receiver
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.entity_identifier
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String entityIdentifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.entity_name
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String entityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.title
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.message_html
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String messageHtml;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.message_stripped
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String messageStripped;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.sender
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String sender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.read_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date readAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.snoozed_till
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date snoozedTill;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.archived_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date archivedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notifications.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.id
     *
     * @return the value of notifications.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.id
     *
     * @param id the value for notifications.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.workspace_id
     *
     * @return the value of notifications.workspace_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getWorkspaceId() {
        return workspaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.workspace_id
     *
     * @param workspaceId the value for notifications.workspace_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId == null ? null : workspaceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.project_id
     *
     * @return the value of notifications.project_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.project_id
     *
     * @param projectId the value for notifications.project_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.triggered_by
     *
     * @return the value of notifications.triggered_by
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getTriggeredBy() {
        return triggeredBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.triggered_by
     *
     * @param triggeredBy the value for notifications.triggered_by
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setTriggeredBy(String triggeredBy) {
        this.triggeredBy = triggeredBy == null ? null : triggeredBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.receiver
     *
     * @return the value of notifications.receiver
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.receiver
     *
     * @param receiver the value for notifications.receiver
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.entity_identifier
     *
     * @return the value of notifications.entity_identifier
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getEntityIdentifier() {
        return entityIdentifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.entity_identifier
     *
     * @param entityIdentifier the value for notifications.entity_identifier
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setEntityIdentifier(String entityIdentifier) {
        this.entityIdentifier = entityIdentifier == null ? null : entityIdentifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.entity_name
     *
     * @return the value of notifications.entity_name
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getEntityName() {
        return entityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.entity_name
     *
     * @param entityName the value for notifications.entity_name
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setEntityName(String entityName) {
        this.entityName = entityName == null ? null : entityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.title
     *
     * @return the value of notifications.title
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.title
     *
     * @param title the value for notifications.title
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.message_html
     *
     * @return the value of notifications.message_html
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getMessageHtml() {
        return messageHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.message_html
     *
     * @param messageHtml the value for notifications.message_html
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setMessageHtml(String messageHtml) {
        this.messageHtml = messageHtml == null ? null : messageHtml.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.message_stripped
     *
     * @return the value of notifications.message_stripped
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getMessageStripped() {
        return messageStripped;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.message_stripped
     *
     * @param messageStripped the value for notifications.message_stripped
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setMessageStripped(String messageStripped) {
        this.messageStripped = messageStripped == null ? null : messageStripped.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.sender
     *
     * @return the value of notifications.sender
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.sender
     *
     * @param sender the value for notifications.sender
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setSender(String sender) {
        this.sender = sender == null ? null : sender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.read_at
     *
     * @return the value of notifications.read_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getReadAt() {
        return readAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.read_at
     *
     * @param readAt the value for notifications.read_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setReadAt(Date readAt) {
        this.readAt = readAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.snoozed_till
     *
     * @return the value of notifications.snoozed_till
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getSnoozedTill() {
        return snoozedTill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.snoozed_till
     *
     * @param snoozedTill the value for notifications.snoozed_till
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setSnoozedTill(Date snoozedTill) {
        this.snoozedTill = snoozedTill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.archived_at
     *
     * @return the value of notifications.archived_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getArchivedAt() {
        return archivedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.archived_at
     *
     * @param archivedAt the value for notifications.archived_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setArchivedAt(Date archivedAt) {
        this.archivedAt = archivedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.created_at
     *
     * @return the value of notifications.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.created_at
     *
     * @param createdAt the value for notifications.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notifications.updated_at
     *
     * @return the value of notifications.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notifications.updated_at
     *
     * @param updatedAt the value for notifications.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}