package com.server.plane.entity;

import java.util.Date;

public class ProjectMemberInvites {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_member_invites.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_member_invites.email
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_member_invites.accepted
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Boolean accepted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_member_invites.token
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_member_invites.responded_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date respondedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_member_invites.role
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Integer role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_member_invites.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_member_invites.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_member_invites.message
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_member_invites.id
     *
     * @return the value of project_member_invites.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_member_invites.id
     *
     * @param id the value for project_member_invites.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_member_invites.email
     *
     * @return the value of project_member_invites.email
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_member_invites.email
     *
     * @param email the value for project_member_invites.email
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_member_invites.accepted
     *
     * @return the value of project_member_invites.accepted
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Boolean getAccepted() {
        return accepted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_member_invites.accepted
     *
     * @param accepted the value for project_member_invites.accepted
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setAccepted(Boolean accepted) {
        this.accepted = accepted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_member_invites.token
     *
     * @return the value of project_member_invites.token
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_member_invites.token
     *
     * @param token the value for project_member_invites.token
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_member_invites.responded_at
     *
     * @return the value of project_member_invites.responded_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getRespondedAt() {
        return respondedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_member_invites.responded_at
     *
     * @param respondedAt the value for project_member_invites.responded_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setRespondedAt(Date respondedAt) {
        this.respondedAt = respondedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_member_invites.role
     *
     * @return the value of project_member_invites.role
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_member_invites.role
     *
     * @param role the value for project_member_invites.role
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_member_invites.created_at
     *
     * @return the value of project_member_invites.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_member_invites.created_at
     *
     * @param createdAt the value for project_member_invites.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_member_invites.updated_at
     *
     * @return the value of project_member_invites.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_member_invites.updated_at
     *
     * @param updatedAt the value for project_member_invites.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_member_invites.message
     *
     * @return the value of project_member_invites.message
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_member_invites.message
     *
     * @param message the value for project_member_invites.message
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }
}