package com.server.plane.entity;

import java.util.Date;

public class Projects {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.created_by
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.estimate_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String estimateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.default_assignee
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String defaultAssignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.project_lead
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String projectLead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.workspace_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String workspaceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.name
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.description
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.network
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Integer network;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.identifier
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String identifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.emoji
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String emoji;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.module_view
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Boolean moduleView;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.cycle_view
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Boolean cycleView;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.issue_views_view
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Boolean issueViewsView;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.page_view
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Boolean pageView;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.inbox_view
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Boolean inboxView;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.archive_in
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Integer archiveIn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.close_in
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Integer closeIn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.createdAt
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date createdat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.updatedAt
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date updatedat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.id
     *
     * @return the value of projects.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.id
     *
     * @param id the value for projects.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.created_by
     *
     * @return the value of projects.created_by
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.created_by
     *
     * @param createdBy the value for projects.created_by
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.estimate_id
     *
     * @return the value of projects.estimate_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getEstimateId() {
        return estimateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.estimate_id
     *
     * @param estimateId the value for projects.estimate_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setEstimateId(String estimateId) {
        this.estimateId = estimateId == null ? null : estimateId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.default_assignee
     *
     * @return the value of projects.default_assignee
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getDefaultAssignee() {
        return defaultAssignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.default_assignee
     *
     * @param defaultAssignee the value for projects.default_assignee
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setDefaultAssignee(String defaultAssignee) {
        this.defaultAssignee = defaultAssignee == null ? null : defaultAssignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.project_lead
     *
     * @return the value of projects.project_lead
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getProjectLead() {
        return projectLead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.project_lead
     *
     * @param projectLead the value for projects.project_lead
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setProjectLead(String projectLead) {
        this.projectLead = projectLead == null ? null : projectLead.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.workspace_id
     *
     * @return the value of projects.workspace_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getWorkspaceId() {
        return workspaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.workspace_id
     *
     * @param workspaceId the value for projects.workspace_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId == null ? null : workspaceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.name
     *
     * @return the value of projects.name
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.name
     *
     * @param name the value for projects.name
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.description
     *
     * @return the value of projects.description
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.description
     *
     * @param description the value for projects.description
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.network
     *
     * @return the value of projects.network
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Integer getNetwork() {
        return network;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.network
     *
     * @param network the value for projects.network
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setNetwork(Integer network) {
        this.network = network;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.identifier
     *
     * @return the value of projects.identifier
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.identifier
     *
     * @param identifier the value for projects.identifier
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier == null ? null : identifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.emoji
     *
     * @return the value of projects.emoji
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getEmoji() {
        return emoji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.emoji
     *
     * @param emoji the value for projects.emoji
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setEmoji(String emoji) {
        this.emoji = emoji == null ? null : emoji.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.module_view
     *
     * @return the value of projects.module_view
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Boolean getModuleView() {
        return moduleView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.module_view
     *
     * @param moduleView the value for projects.module_view
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setModuleView(Boolean moduleView) {
        this.moduleView = moduleView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.cycle_view
     *
     * @return the value of projects.cycle_view
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Boolean getCycleView() {
        return cycleView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.cycle_view
     *
     * @param cycleView the value for projects.cycle_view
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setCycleView(Boolean cycleView) {
        this.cycleView = cycleView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.issue_views_view
     *
     * @return the value of projects.issue_views_view
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Boolean getIssueViewsView() {
        return issueViewsView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.issue_views_view
     *
     * @param issueViewsView the value for projects.issue_views_view
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setIssueViewsView(Boolean issueViewsView) {
        this.issueViewsView = issueViewsView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.page_view
     *
     * @return the value of projects.page_view
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Boolean getPageView() {
        return pageView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.page_view
     *
     * @param pageView the value for projects.page_view
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setPageView(Boolean pageView) {
        this.pageView = pageView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.inbox_view
     *
     * @return the value of projects.inbox_view
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Boolean getInboxView() {
        return inboxView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.inbox_view
     *
     * @param inboxView the value for projects.inbox_view
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setInboxView(Boolean inboxView) {
        this.inboxView = inboxView;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.archive_in
     *
     * @return the value of projects.archive_in
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Integer getArchiveIn() {
        return archiveIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.archive_in
     *
     * @param archiveIn the value for projects.archive_in
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setArchiveIn(Integer archiveIn) {
        this.archiveIn = archiveIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.close_in
     *
     * @return the value of projects.close_in
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Integer getCloseIn() {
        return closeIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.close_in
     *
     * @param closeIn the value for projects.close_in
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setCloseIn(Integer closeIn) {
        this.closeIn = closeIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.createdAt
     *
     * @return the value of projects.createdAt
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.createdAt
     *
     * @param createdat the value for projects.createdAt
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.updatedAt
     *
     * @return the value of projects.updatedAt
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getUpdatedat() {
        return updatedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.updatedAt
     *
     * @param updatedat the value for projects.updatedAt
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setUpdatedat(Date updatedat) {
        this.updatedat = updatedat;
    }
}