package com.server.plane.entity;

import java.util.Date;

public class ProjectMembers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_members.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_members.member
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String member;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_members.project_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_members.workspace_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String workspaceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_members.comment
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_members.role
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Integer role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_members.sort_order
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_members.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_members.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_members.id
     *
     * @return the value of project_members.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_members.id
     *
     * @param id the value for project_members.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_members.member
     *
     * @return the value of project_members.member
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getMember() {
        return member;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_members.member
     *
     * @param member the value for project_members.member
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setMember(String member) {
        this.member = member == null ? null : member.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_members.project_id
     *
     * @return the value of project_members.project_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_members.project_id
     *
     * @param projectId the value for project_members.project_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_members.workspace_id
     *
     * @return the value of project_members.workspace_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getWorkspaceId() {
        return workspaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_members.workspace_id
     *
     * @param workspaceId the value for project_members.workspace_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId == null ? null : workspaceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_members.comment
     *
     * @return the value of project_members.comment
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_members.comment
     *
     * @param comment the value for project_members.comment
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_members.role
     *
     * @return the value of project_members.role
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_members.role
     *
     * @param role the value for project_members.role
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_members.sort_order
     *
     * @return the value of project_members.sort_order
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_members.sort_order
     *
     * @param sortOrder the value for project_members.sort_order
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setSortOrder(String sortOrder) {
        this.sortOrder = sortOrder == null ? null : sortOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_members.created_at
     *
     * @return the value of project_members.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_members.created_at
     *
     * @param createdAt the value for project_members.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_members.updated_at
     *
     * @return the value of project_members.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_members.updated_at
     *
     * @param updatedAt the value for project_members.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}