package com.server.plane.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProjectsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table projects
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table projects
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table projects
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public ProjectsExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projects
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table projects
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("created_by is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("created_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("created_by =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("created_by <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("created_by >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("created_by >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("created_by <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("created_by <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("created_by like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("created_by not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("created_by in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("created_by not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("created_by between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("created_by not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andEstimateIdIsNull() {
            addCriterion("estimate_id is null");
            return (Criteria) this;
        }

        public Criteria andEstimateIdIsNotNull() {
            addCriterion("estimate_id is not null");
            return (Criteria) this;
        }

        public Criteria andEstimateIdEqualTo(String value) {
            addCriterion("estimate_id =", value, "estimateId");
            return (Criteria) this;
        }

        public Criteria andEstimateIdNotEqualTo(String value) {
            addCriterion("estimate_id <>", value, "estimateId");
            return (Criteria) this;
        }

        public Criteria andEstimateIdGreaterThan(String value) {
            addCriterion("estimate_id >", value, "estimateId");
            return (Criteria) this;
        }

        public Criteria andEstimateIdGreaterThanOrEqualTo(String value) {
            addCriterion("estimate_id >=", value, "estimateId");
            return (Criteria) this;
        }

        public Criteria andEstimateIdLessThan(String value) {
            addCriterion("estimate_id <", value, "estimateId");
            return (Criteria) this;
        }

        public Criteria andEstimateIdLessThanOrEqualTo(String value) {
            addCriterion("estimate_id <=", value, "estimateId");
            return (Criteria) this;
        }

        public Criteria andEstimateIdLike(String value) {
            addCriterion("estimate_id like", value, "estimateId");
            return (Criteria) this;
        }

        public Criteria andEstimateIdNotLike(String value) {
            addCriterion("estimate_id not like", value, "estimateId");
            return (Criteria) this;
        }

        public Criteria andEstimateIdIn(List<String> values) {
            addCriterion("estimate_id in", values, "estimateId");
            return (Criteria) this;
        }

        public Criteria andEstimateIdNotIn(List<String> values) {
            addCriterion("estimate_id not in", values, "estimateId");
            return (Criteria) this;
        }

        public Criteria andEstimateIdBetween(String value1, String value2) {
            addCriterion("estimate_id between", value1, value2, "estimateId");
            return (Criteria) this;
        }

        public Criteria andEstimateIdNotBetween(String value1, String value2) {
            addCriterion("estimate_id not between", value1, value2, "estimateId");
            return (Criteria) this;
        }

        public Criteria andDefaultAssigneeIsNull() {
            addCriterion("default_assignee is null");
            return (Criteria) this;
        }

        public Criteria andDefaultAssigneeIsNotNull() {
            addCriterion("default_assignee is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultAssigneeEqualTo(String value) {
            addCriterion("default_assignee =", value, "defaultAssignee");
            return (Criteria) this;
        }

        public Criteria andDefaultAssigneeNotEqualTo(String value) {
            addCriterion("default_assignee <>", value, "defaultAssignee");
            return (Criteria) this;
        }

        public Criteria andDefaultAssigneeGreaterThan(String value) {
            addCriterion("default_assignee >", value, "defaultAssignee");
            return (Criteria) this;
        }

        public Criteria andDefaultAssigneeGreaterThanOrEqualTo(String value) {
            addCriterion("default_assignee >=", value, "defaultAssignee");
            return (Criteria) this;
        }

        public Criteria andDefaultAssigneeLessThan(String value) {
            addCriterion("default_assignee <", value, "defaultAssignee");
            return (Criteria) this;
        }

        public Criteria andDefaultAssigneeLessThanOrEqualTo(String value) {
            addCriterion("default_assignee <=", value, "defaultAssignee");
            return (Criteria) this;
        }

        public Criteria andDefaultAssigneeLike(String value) {
            addCriterion("default_assignee like", value, "defaultAssignee");
            return (Criteria) this;
        }

        public Criteria andDefaultAssigneeNotLike(String value) {
            addCriterion("default_assignee not like", value, "defaultAssignee");
            return (Criteria) this;
        }

        public Criteria andDefaultAssigneeIn(List<String> values) {
            addCriterion("default_assignee in", values, "defaultAssignee");
            return (Criteria) this;
        }

        public Criteria andDefaultAssigneeNotIn(List<String> values) {
            addCriterion("default_assignee not in", values, "defaultAssignee");
            return (Criteria) this;
        }

        public Criteria andDefaultAssigneeBetween(String value1, String value2) {
            addCriterion("default_assignee between", value1, value2, "defaultAssignee");
            return (Criteria) this;
        }

        public Criteria andDefaultAssigneeNotBetween(String value1, String value2) {
            addCriterion("default_assignee not between", value1, value2, "defaultAssignee");
            return (Criteria) this;
        }

        public Criteria andProjectLeadIsNull() {
            addCriterion("project_lead is null");
            return (Criteria) this;
        }

        public Criteria andProjectLeadIsNotNull() {
            addCriterion("project_lead is not null");
            return (Criteria) this;
        }

        public Criteria andProjectLeadEqualTo(String value) {
            addCriterion("project_lead =", value, "projectLead");
            return (Criteria) this;
        }

        public Criteria andProjectLeadNotEqualTo(String value) {
            addCriterion("project_lead <>", value, "projectLead");
            return (Criteria) this;
        }

        public Criteria andProjectLeadGreaterThan(String value) {
            addCriterion("project_lead >", value, "projectLead");
            return (Criteria) this;
        }

        public Criteria andProjectLeadGreaterThanOrEqualTo(String value) {
            addCriterion("project_lead >=", value, "projectLead");
            return (Criteria) this;
        }

        public Criteria andProjectLeadLessThan(String value) {
            addCriterion("project_lead <", value, "projectLead");
            return (Criteria) this;
        }

        public Criteria andProjectLeadLessThanOrEqualTo(String value) {
            addCriterion("project_lead <=", value, "projectLead");
            return (Criteria) this;
        }

        public Criteria andProjectLeadLike(String value) {
            addCriterion("project_lead like", value, "projectLead");
            return (Criteria) this;
        }

        public Criteria andProjectLeadNotLike(String value) {
            addCriterion("project_lead not like", value, "projectLead");
            return (Criteria) this;
        }

        public Criteria andProjectLeadIn(List<String> values) {
            addCriterion("project_lead in", values, "projectLead");
            return (Criteria) this;
        }

        public Criteria andProjectLeadNotIn(List<String> values) {
            addCriterion("project_lead not in", values, "projectLead");
            return (Criteria) this;
        }

        public Criteria andProjectLeadBetween(String value1, String value2) {
            addCriterion("project_lead between", value1, value2, "projectLead");
            return (Criteria) this;
        }

        public Criteria andProjectLeadNotBetween(String value1, String value2) {
            addCriterion("project_lead not between", value1, value2, "projectLead");
            return (Criteria) this;
        }

        public Criteria andWorkspaceIdIsNull() {
            addCriterion("workspace_id is null");
            return (Criteria) this;
        }

        public Criteria andWorkspaceIdIsNotNull() {
            addCriterion("workspace_id is not null");
            return (Criteria) this;
        }

        public Criteria andWorkspaceIdEqualTo(String value) {
            addCriterion("workspace_id =", value, "workspaceId");
            return (Criteria) this;
        }

        public Criteria andWorkspaceIdNotEqualTo(String value) {
            addCriterion("workspace_id <>", value, "workspaceId");
            return (Criteria) this;
        }

        public Criteria andWorkspaceIdGreaterThan(String value) {
            addCriterion("workspace_id >", value, "workspaceId");
            return (Criteria) this;
        }

        public Criteria andWorkspaceIdGreaterThanOrEqualTo(String value) {
            addCriterion("workspace_id >=", value, "workspaceId");
            return (Criteria) this;
        }

        public Criteria andWorkspaceIdLessThan(String value) {
            addCriterion("workspace_id <", value, "workspaceId");
            return (Criteria) this;
        }

        public Criteria andWorkspaceIdLessThanOrEqualTo(String value) {
            addCriterion("workspace_id <=", value, "workspaceId");
            return (Criteria) this;
        }

        public Criteria andWorkspaceIdLike(String value) {
            addCriterion("workspace_id like", value, "workspaceId");
            return (Criteria) this;
        }

        public Criteria andWorkspaceIdNotLike(String value) {
            addCriterion("workspace_id not like", value, "workspaceId");
            return (Criteria) this;
        }

        public Criteria andWorkspaceIdIn(List<String> values) {
            addCriterion("workspace_id in", values, "workspaceId");
            return (Criteria) this;
        }

        public Criteria andWorkspaceIdNotIn(List<String> values) {
            addCriterion("workspace_id not in", values, "workspaceId");
            return (Criteria) this;
        }

        public Criteria andWorkspaceIdBetween(String value1, String value2) {
            addCriterion("workspace_id between", value1, value2, "workspaceId");
            return (Criteria) this;
        }

        public Criteria andWorkspaceIdNotBetween(String value1, String value2) {
            addCriterion("workspace_id not between", value1, value2, "workspaceId");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("\"name\" is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("\"name\" is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("\"name\" =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("\"name\" <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("\"name\" >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("\"name\" >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("\"name\" <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("\"name\" <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("\"name\" like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("\"name\" not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("\"name\" in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("\"name\" not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("\"name\" between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("\"name\" not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andNetworkIsNull() {
            addCriterion("network is null");
            return (Criteria) this;
        }

        public Criteria andNetworkIsNotNull() {
            addCriterion("network is not null");
            return (Criteria) this;
        }

        public Criteria andNetworkEqualTo(Integer value) {
            addCriterion("network =", value, "network");
            return (Criteria) this;
        }

        public Criteria andNetworkNotEqualTo(Integer value) {
            addCriterion("network <>", value, "network");
            return (Criteria) this;
        }

        public Criteria andNetworkGreaterThan(Integer value) {
            addCriterion("network >", value, "network");
            return (Criteria) this;
        }

        public Criteria andNetworkGreaterThanOrEqualTo(Integer value) {
            addCriterion("network >=", value, "network");
            return (Criteria) this;
        }

        public Criteria andNetworkLessThan(Integer value) {
            addCriterion("network <", value, "network");
            return (Criteria) this;
        }

        public Criteria andNetworkLessThanOrEqualTo(Integer value) {
            addCriterion("network <=", value, "network");
            return (Criteria) this;
        }

        public Criteria andNetworkIn(List<Integer> values) {
            addCriterion("network in", values, "network");
            return (Criteria) this;
        }

        public Criteria andNetworkNotIn(List<Integer> values) {
            addCriterion("network not in", values, "network");
            return (Criteria) this;
        }

        public Criteria andNetworkBetween(Integer value1, Integer value2) {
            addCriterion("network between", value1, value2, "network");
            return (Criteria) this;
        }

        public Criteria andNetworkNotBetween(Integer value1, Integer value2) {
            addCriterion("network not between", value1, value2, "network");
            return (Criteria) this;
        }

        public Criteria andIdentifierIsNull() {
            addCriterion("identifier is null");
            return (Criteria) this;
        }

        public Criteria andIdentifierIsNotNull() {
            addCriterion("identifier is not null");
            return (Criteria) this;
        }

        public Criteria andIdentifierEqualTo(String value) {
            addCriterion("identifier =", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierNotEqualTo(String value) {
            addCriterion("identifier <>", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierGreaterThan(String value) {
            addCriterion("identifier >", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierGreaterThanOrEqualTo(String value) {
            addCriterion("identifier >=", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierLessThan(String value) {
            addCriterion("identifier <", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierLessThanOrEqualTo(String value) {
            addCriterion("identifier <=", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierLike(String value) {
            addCriterion("identifier like", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierNotLike(String value) {
            addCriterion("identifier not like", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierIn(List<String> values) {
            addCriterion("identifier in", values, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierNotIn(List<String> values) {
            addCriterion("identifier not in", values, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierBetween(String value1, String value2) {
            addCriterion("identifier between", value1, value2, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierNotBetween(String value1, String value2) {
            addCriterion("identifier not between", value1, value2, "identifier");
            return (Criteria) this;
        }

        public Criteria andEmojiIsNull() {
            addCriterion("emoji is null");
            return (Criteria) this;
        }

        public Criteria andEmojiIsNotNull() {
            addCriterion("emoji is not null");
            return (Criteria) this;
        }

        public Criteria andEmojiEqualTo(String value) {
            addCriterion("emoji =", value, "emoji");
            return (Criteria) this;
        }

        public Criteria andEmojiNotEqualTo(String value) {
            addCriterion("emoji <>", value, "emoji");
            return (Criteria) this;
        }

        public Criteria andEmojiGreaterThan(String value) {
            addCriterion("emoji >", value, "emoji");
            return (Criteria) this;
        }

        public Criteria andEmojiGreaterThanOrEqualTo(String value) {
            addCriterion("emoji >=", value, "emoji");
            return (Criteria) this;
        }

        public Criteria andEmojiLessThan(String value) {
            addCriterion("emoji <", value, "emoji");
            return (Criteria) this;
        }

        public Criteria andEmojiLessThanOrEqualTo(String value) {
            addCriterion("emoji <=", value, "emoji");
            return (Criteria) this;
        }

        public Criteria andEmojiLike(String value) {
            addCriterion("emoji like", value, "emoji");
            return (Criteria) this;
        }

        public Criteria andEmojiNotLike(String value) {
            addCriterion("emoji not like", value, "emoji");
            return (Criteria) this;
        }

        public Criteria andEmojiIn(List<String> values) {
            addCriterion("emoji in", values, "emoji");
            return (Criteria) this;
        }

        public Criteria andEmojiNotIn(List<String> values) {
            addCriterion("emoji not in", values, "emoji");
            return (Criteria) this;
        }

        public Criteria andEmojiBetween(String value1, String value2) {
            addCriterion("emoji between", value1, value2, "emoji");
            return (Criteria) this;
        }

        public Criteria andEmojiNotBetween(String value1, String value2) {
            addCriterion("emoji not between", value1, value2, "emoji");
            return (Criteria) this;
        }

        public Criteria andModuleViewIsNull() {
            addCriterion("module_view is null");
            return (Criteria) this;
        }

        public Criteria andModuleViewIsNotNull() {
            addCriterion("module_view is not null");
            return (Criteria) this;
        }

        public Criteria andModuleViewEqualTo(Boolean value) {
            addCriterion("module_view =", value, "moduleView");
            return (Criteria) this;
        }

        public Criteria andModuleViewNotEqualTo(Boolean value) {
            addCriterion("module_view <>", value, "moduleView");
            return (Criteria) this;
        }

        public Criteria andModuleViewGreaterThan(Boolean value) {
            addCriterion("module_view >", value, "moduleView");
            return (Criteria) this;
        }

        public Criteria andModuleViewGreaterThanOrEqualTo(Boolean value) {
            addCriterion("module_view >=", value, "moduleView");
            return (Criteria) this;
        }

        public Criteria andModuleViewLessThan(Boolean value) {
            addCriterion("module_view <", value, "moduleView");
            return (Criteria) this;
        }

        public Criteria andModuleViewLessThanOrEqualTo(Boolean value) {
            addCriterion("module_view <=", value, "moduleView");
            return (Criteria) this;
        }

        public Criteria andModuleViewIn(List<Boolean> values) {
            addCriterion("module_view in", values, "moduleView");
            return (Criteria) this;
        }

        public Criteria andModuleViewNotIn(List<Boolean> values) {
            addCriterion("module_view not in", values, "moduleView");
            return (Criteria) this;
        }

        public Criteria andModuleViewBetween(Boolean value1, Boolean value2) {
            addCriterion("module_view between", value1, value2, "moduleView");
            return (Criteria) this;
        }

        public Criteria andModuleViewNotBetween(Boolean value1, Boolean value2) {
            addCriterion("module_view not between", value1, value2, "moduleView");
            return (Criteria) this;
        }

        public Criteria andCycleViewIsNull() {
            addCriterion("cycle_view is null");
            return (Criteria) this;
        }

        public Criteria andCycleViewIsNotNull() {
            addCriterion("cycle_view is not null");
            return (Criteria) this;
        }

        public Criteria andCycleViewEqualTo(Boolean value) {
            addCriterion("cycle_view =", value, "cycleView");
            return (Criteria) this;
        }

        public Criteria andCycleViewNotEqualTo(Boolean value) {
            addCriterion("cycle_view <>", value, "cycleView");
            return (Criteria) this;
        }

        public Criteria andCycleViewGreaterThan(Boolean value) {
            addCriterion("cycle_view >", value, "cycleView");
            return (Criteria) this;
        }

        public Criteria andCycleViewGreaterThanOrEqualTo(Boolean value) {
            addCriterion("cycle_view >=", value, "cycleView");
            return (Criteria) this;
        }

        public Criteria andCycleViewLessThan(Boolean value) {
            addCriterion("cycle_view <", value, "cycleView");
            return (Criteria) this;
        }

        public Criteria andCycleViewLessThanOrEqualTo(Boolean value) {
            addCriterion("cycle_view <=", value, "cycleView");
            return (Criteria) this;
        }

        public Criteria andCycleViewIn(List<Boolean> values) {
            addCriterion("cycle_view in", values, "cycleView");
            return (Criteria) this;
        }

        public Criteria andCycleViewNotIn(List<Boolean> values) {
            addCriterion("cycle_view not in", values, "cycleView");
            return (Criteria) this;
        }

        public Criteria andCycleViewBetween(Boolean value1, Boolean value2) {
            addCriterion("cycle_view between", value1, value2, "cycleView");
            return (Criteria) this;
        }

        public Criteria andCycleViewNotBetween(Boolean value1, Boolean value2) {
            addCriterion("cycle_view not between", value1, value2, "cycleView");
            return (Criteria) this;
        }

        public Criteria andIssueViewsViewIsNull() {
            addCriterion("issue_views_view is null");
            return (Criteria) this;
        }

        public Criteria andIssueViewsViewIsNotNull() {
            addCriterion("issue_views_view is not null");
            return (Criteria) this;
        }

        public Criteria andIssueViewsViewEqualTo(Boolean value) {
            addCriterion("issue_views_view =", value, "issueViewsView");
            return (Criteria) this;
        }

        public Criteria andIssueViewsViewNotEqualTo(Boolean value) {
            addCriterion("issue_views_view <>", value, "issueViewsView");
            return (Criteria) this;
        }

        public Criteria andIssueViewsViewGreaterThan(Boolean value) {
            addCriterion("issue_views_view >", value, "issueViewsView");
            return (Criteria) this;
        }

        public Criteria andIssueViewsViewGreaterThanOrEqualTo(Boolean value) {
            addCriterion("issue_views_view >=", value, "issueViewsView");
            return (Criteria) this;
        }

        public Criteria andIssueViewsViewLessThan(Boolean value) {
            addCriterion("issue_views_view <", value, "issueViewsView");
            return (Criteria) this;
        }

        public Criteria andIssueViewsViewLessThanOrEqualTo(Boolean value) {
            addCriterion("issue_views_view <=", value, "issueViewsView");
            return (Criteria) this;
        }

        public Criteria andIssueViewsViewIn(List<Boolean> values) {
            addCriterion("issue_views_view in", values, "issueViewsView");
            return (Criteria) this;
        }

        public Criteria andIssueViewsViewNotIn(List<Boolean> values) {
            addCriterion("issue_views_view not in", values, "issueViewsView");
            return (Criteria) this;
        }

        public Criteria andIssueViewsViewBetween(Boolean value1, Boolean value2) {
            addCriterion("issue_views_view between", value1, value2, "issueViewsView");
            return (Criteria) this;
        }

        public Criteria andIssueViewsViewNotBetween(Boolean value1, Boolean value2) {
            addCriterion("issue_views_view not between", value1, value2, "issueViewsView");
            return (Criteria) this;
        }

        public Criteria andPageViewIsNull() {
            addCriterion("page_view is null");
            return (Criteria) this;
        }

        public Criteria andPageViewIsNotNull() {
            addCriterion("page_view is not null");
            return (Criteria) this;
        }

        public Criteria andPageViewEqualTo(Boolean value) {
            addCriterion("page_view =", value, "pageView");
            return (Criteria) this;
        }

        public Criteria andPageViewNotEqualTo(Boolean value) {
            addCriterion("page_view <>", value, "pageView");
            return (Criteria) this;
        }

        public Criteria andPageViewGreaterThan(Boolean value) {
            addCriterion("page_view >", value, "pageView");
            return (Criteria) this;
        }

        public Criteria andPageViewGreaterThanOrEqualTo(Boolean value) {
            addCriterion("page_view >=", value, "pageView");
            return (Criteria) this;
        }

        public Criteria andPageViewLessThan(Boolean value) {
            addCriterion("page_view <", value, "pageView");
            return (Criteria) this;
        }

        public Criteria andPageViewLessThanOrEqualTo(Boolean value) {
            addCriterion("page_view <=", value, "pageView");
            return (Criteria) this;
        }

        public Criteria andPageViewIn(List<Boolean> values) {
            addCriterion("page_view in", values, "pageView");
            return (Criteria) this;
        }

        public Criteria andPageViewNotIn(List<Boolean> values) {
            addCriterion("page_view not in", values, "pageView");
            return (Criteria) this;
        }

        public Criteria andPageViewBetween(Boolean value1, Boolean value2) {
            addCriterion("page_view between", value1, value2, "pageView");
            return (Criteria) this;
        }

        public Criteria andPageViewNotBetween(Boolean value1, Boolean value2) {
            addCriterion("page_view not between", value1, value2, "pageView");
            return (Criteria) this;
        }

        public Criteria andInboxViewIsNull() {
            addCriterion("inbox_view is null");
            return (Criteria) this;
        }

        public Criteria andInboxViewIsNotNull() {
            addCriterion("inbox_view is not null");
            return (Criteria) this;
        }

        public Criteria andInboxViewEqualTo(Boolean value) {
            addCriterion("inbox_view =", value, "inboxView");
            return (Criteria) this;
        }

        public Criteria andInboxViewNotEqualTo(Boolean value) {
            addCriterion("inbox_view <>", value, "inboxView");
            return (Criteria) this;
        }

        public Criteria andInboxViewGreaterThan(Boolean value) {
            addCriterion("inbox_view >", value, "inboxView");
            return (Criteria) this;
        }

        public Criteria andInboxViewGreaterThanOrEqualTo(Boolean value) {
            addCriterion("inbox_view >=", value, "inboxView");
            return (Criteria) this;
        }

        public Criteria andInboxViewLessThan(Boolean value) {
            addCriterion("inbox_view <", value, "inboxView");
            return (Criteria) this;
        }

        public Criteria andInboxViewLessThanOrEqualTo(Boolean value) {
            addCriterion("inbox_view <=", value, "inboxView");
            return (Criteria) this;
        }

        public Criteria andInboxViewIn(List<Boolean> values) {
            addCriterion("inbox_view in", values, "inboxView");
            return (Criteria) this;
        }

        public Criteria andInboxViewNotIn(List<Boolean> values) {
            addCriterion("inbox_view not in", values, "inboxView");
            return (Criteria) this;
        }

        public Criteria andInboxViewBetween(Boolean value1, Boolean value2) {
            addCriterion("inbox_view between", value1, value2, "inboxView");
            return (Criteria) this;
        }

        public Criteria andInboxViewNotBetween(Boolean value1, Boolean value2) {
            addCriterion("inbox_view not between", value1, value2, "inboxView");
            return (Criteria) this;
        }

        public Criteria andArchiveInIsNull() {
            addCriterion("archive_in is null");
            return (Criteria) this;
        }

        public Criteria andArchiveInIsNotNull() {
            addCriterion("archive_in is not null");
            return (Criteria) this;
        }

        public Criteria andArchiveInEqualTo(Integer value) {
            addCriterion("archive_in =", value, "archiveIn");
            return (Criteria) this;
        }

        public Criteria andArchiveInNotEqualTo(Integer value) {
            addCriterion("archive_in <>", value, "archiveIn");
            return (Criteria) this;
        }

        public Criteria andArchiveInGreaterThan(Integer value) {
            addCriterion("archive_in >", value, "archiveIn");
            return (Criteria) this;
        }

        public Criteria andArchiveInGreaterThanOrEqualTo(Integer value) {
            addCriterion("archive_in >=", value, "archiveIn");
            return (Criteria) this;
        }

        public Criteria andArchiveInLessThan(Integer value) {
            addCriterion("archive_in <", value, "archiveIn");
            return (Criteria) this;
        }

        public Criteria andArchiveInLessThanOrEqualTo(Integer value) {
            addCriterion("archive_in <=", value, "archiveIn");
            return (Criteria) this;
        }

        public Criteria andArchiveInIn(List<Integer> values) {
            addCriterion("archive_in in", values, "archiveIn");
            return (Criteria) this;
        }

        public Criteria andArchiveInNotIn(List<Integer> values) {
            addCriterion("archive_in not in", values, "archiveIn");
            return (Criteria) this;
        }

        public Criteria andArchiveInBetween(Integer value1, Integer value2) {
            addCriterion("archive_in between", value1, value2, "archiveIn");
            return (Criteria) this;
        }

        public Criteria andArchiveInNotBetween(Integer value1, Integer value2) {
            addCriterion("archive_in not between", value1, value2, "archiveIn");
            return (Criteria) this;
        }

        public Criteria andCloseInIsNull() {
            addCriterion("close_in is null");
            return (Criteria) this;
        }

        public Criteria andCloseInIsNotNull() {
            addCriterion("close_in is not null");
            return (Criteria) this;
        }

        public Criteria andCloseInEqualTo(Integer value) {
            addCriterion("close_in =", value, "closeIn");
            return (Criteria) this;
        }

        public Criteria andCloseInNotEqualTo(Integer value) {
            addCriterion("close_in <>", value, "closeIn");
            return (Criteria) this;
        }

        public Criteria andCloseInGreaterThan(Integer value) {
            addCriterion("close_in >", value, "closeIn");
            return (Criteria) this;
        }

        public Criteria andCloseInGreaterThanOrEqualTo(Integer value) {
            addCriterion("close_in >=", value, "closeIn");
            return (Criteria) this;
        }

        public Criteria andCloseInLessThan(Integer value) {
            addCriterion("close_in <", value, "closeIn");
            return (Criteria) this;
        }

        public Criteria andCloseInLessThanOrEqualTo(Integer value) {
            addCriterion("close_in <=", value, "closeIn");
            return (Criteria) this;
        }

        public Criteria andCloseInIn(List<Integer> values) {
            addCriterion("close_in in", values, "closeIn");
            return (Criteria) this;
        }

        public Criteria andCloseInNotIn(List<Integer> values) {
            addCriterion("close_in not in", values, "closeIn");
            return (Criteria) this;
        }

        public Criteria andCloseInBetween(Integer value1, Integer value2) {
            addCriterion("close_in between", value1, value2, "closeIn");
            return (Criteria) this;
        }

        public Criteria andCloseInNotBetween(Integer value1, Integer value2) {
            addCriterion("close_in not between", value1, value2, "closeIn");
            return (Criteria) this;
        }

        public Criteria andCreatedatIsNull() {
            addCriterion("createdAt is null");
            return (Criteria) this;
        }

        public Criteria andCreatedatIsNotNull() {
            addCriterion("createdAt is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedatEqualTo(Date value) {
            addCriterion("createdAt =", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatNotEqualTo(Date value) {
            addCriterion("createdAt <>", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatGreaterThan(Date value) {
            addCriterion("createdAt >", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatGreaterThanOrEqualTo(Date value) {
            addCriterion("createdAt >=", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatLessThan(Date value) {
            addCriterion("createdAt <", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatLessThanOrEqualTo(Date value) {
            addCriterion("createdAt <=", value, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatIn(List<Date> values) {
            addCriterion("createdAt in", values, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatNotIn(List<Date> values) {
            addCriterion("createdAt not in", values, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatBetween(Date value1, Date value2) {
            addCriterion("createdAt between", value1, value2, "createdat");
            return (Criteria) this;
        }

        public Criteria andCreatedatNotBetween(Date value1, Date value2) {
            addCriterion("createdAt not between", value1, value2, "createdat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatIsNull() {
            addCriterion("updatedAt is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedatIsNotNull() {
            addCriterion("updatedAt is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedatEqualTo(Date value) {
            addCriterion("updatedAt =", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatNotEqualTo(Date value) {
            addCriterion("updatedAt <>", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatGreaterThan(Date value) {
            addCriterion("updatedAt >", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatGreaterThanOrEqualTo(Date value) {
            addCriterion("updatedAt >=", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatLessThan(Date value) {
            addCriterion("updatedAt <", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatLessThanOrEqualTo(Date value) {
            addCriterion("updatedAt <=", value, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatIn(List<Date> values) {
            addCriterion("updatedAt in", values, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatNotIn(List<Date> values) {
            addCriterion("updatedAt not in", values, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatBetween(Date value1, Date value2) {
            addCriterion("updatedAt between", value1, value2, "updatedat");
            return (Criteria) this;
        }

        public Criteria andUpdatedatNotBetween(Date value1, Date value2) {
            addCriterion("updatedAt not between", value1, value2, "updatedat");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table projects
     *
     * @mbg.generated do_not_delete_during_merge Tue Dec 23 23:56:04 ICT 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table projects
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}