package com.server.plane.entity;

public class ProjectMembersWithBLOBs extends ProjectMembers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_members.view_props
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String viewProps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_members.default_props
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String defaultProps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_members.preferences
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String preferences;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_members.view_props
     *
     * @return the value of project_members.view_props
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getViewProps() {
        return viewProps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_members.view_props
     *
     * @param viewProps the value for project_members.view_props
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setViewProps(String viewProps) {
        this.viewProps = viewProps == null ? null : viewProps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_members.default_props
     *
     * @return the value of project_members.default_props
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getDefaultProps() {
        return defaultProps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_members.default_props
     *
     * @param defaultProps the value for project_members.default_props
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setDefaultProps(String defaultProps) {
        this.defaultProps = defaultProps == null ? null : defaultProps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_members.preferences
     *
     * @return the value of project_members.preferences
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getPreferences() {
        return preferences;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_members.preferences
     *
     * @param preferences the value for project_members.preferences
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setPreferences(String preferences) {
        this.preferences = preferences == null ? null : preferences.trim();
    }
}