package com.server.plane.entity;

public class ProjectsWithBLOBs extends Projects {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.description_text
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String descriptionText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.description_html
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String descriptionHtml;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.icon_prop
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String iconProp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column projects.cover_image
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String coverImage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.description_text
     *
     * @return the value of projects.description_text
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getDescriptionText() {
        return descriptionText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.description_text
     *
     * @param descriptionText the value for projects.description_text
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setDescriptionText(String descriptionText) {
        this.descriptionText = descriptionText == null ? null : descriptionText.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.description_html
     *
     * @return the value of projects.description_html
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getDescriptionHtml() {
        return descriptionHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.description_html
     *
     * @param descriptionHtml the value for projects.description_html
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setDescriptionHtml(String descriptionHtml) {
        this.descriptionHtml = descriptionHtml == null ? null : descriptionHtml.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.icon_prop
     *
     * @return the value of projects.icon_prop
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getIconProp() {
        return iconProp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.icon_prop
     *
     * @param iconProp the value for projects.icon_prop
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setIconProp(String iconProp) {
        this.iconProp = iconProp == null ? null : iconProp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column projects.cover_image
     *
     * @return the value of projects.cover_image
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getCoverImage() {
        return coverImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column projects.cover_image
     *
     * @param coverImage the value for projects.cover_image
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setCoverImage(String coverImage) {
        this.coverImage = coverImage == null ? null : coverImage.trim();
    }
}