package com.server.plane.entity;

import java.util.Date;

public class States {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column states.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column states.project_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column states.created_by
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column states.name
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column states.color
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column states.slug
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String slug;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column states.sequence
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Float sequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column states.group_name
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column states.is_default
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Boolean isDefault;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column states.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column states.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column states.description
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column states.id
     *
     * @return the value of states.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column states.id
     *
     * @param id the value for states.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column states.project_id
     *
     * @return the value of states.project_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column states.project_id
     *
     * @param projectId the value for states.project_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column states.created_by
     *
     * @return the value of states.created_by
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column states.created_by
     *
     * @param createdBy the value for states.created_by
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column states.name
     *
     * @return the value of states.name
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column states.name
     *
     * @param name the value for states.name
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column states.color
     *
     * @return the value of states.color
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column states.color
     *
     * @param color the value for states.color
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column states.slug
     *
     * @return the value of states.slug
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getSlug() {
        return slug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column states.slug
     *
     * @param slug the value for states.slug
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setSlug(String slug) {
        this.slug = slug == null ? null : slug.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column states.sequence
     *
     * @return the value of states.sequence
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Float getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column states.sequence
     *
     * @param sequence the value for states.sequence
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setSequence(Float sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column states.group_name
     *
     * @return the value of states.group_name
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column states.group_name
     *
     * @param groupName the value for states.group_name
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column states.is_default
     *
     * @return the value of states.is_default
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Boolean getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column states.is_default
     *
     * @param isDefault the value for states.is_default
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column states.created_at
     *
     * @return the value of states.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column states.created_at
     *
     * @param createdAt the value for states.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column states.updated_at
     *
     * @return the value of states.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column states.updated_at
     *
     * @param updatedAt the value for states.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column states.description
     *
     * @return the value of states.description
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column states.description
     *
     * @param description the value for states.description
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}