package com.server.plane.entity;

public class UsersWithBLOBs extends Users {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.my_issues_prop
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String myIssuesProp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.theme
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String theme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.onboarding_step
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String onboardingStep;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.my_issues_prop
     *
     * @return the value of users.my_issues_prop
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getMyIssuesProp() {
        return myIssuesProp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.my_issues_prop
     *
     * @param myIssuesProp the value for users.my_issues_prop
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setMyIssuesProp(String myIssuesProp) {
        this.myIssuesProp = myIssuesProp == null ? null : myIssuesProp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.theme
     *
     * @return the value of users.theme
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.theme
     *
     * @param theme the value for users.theme
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setTheme(String theme) {
        this.theme = theme == null ? null : theme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.onboarding_step
     *
     * @return the value of users.onboarding_step
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getOnboardingStep() {
        return onboardingStep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.onboarding_step
     *
     * @param onboardingStep the value for users.onboarding_step
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setOnboardingStep(String onboardingStep) {
        this.onboardingStep = onboardingStep == null ? null : onboardingStep.trim();
    }
}