package com.server.plane.entity;

public class WorkspaceMembersWithBLOBs extends WorkspaceMembers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workspace_members.company_role
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String companyRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workspace_members.view_props
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String viewProps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workspace_members.default_props
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String defaultProps;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workspace_members.company_role
     *
     * @return the value of workspace_members.company_role
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getCompanyRole() {
        return companyRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workspace_members.company_role
     *
     * @param companyRole the value for workspace_members.company_role
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setCompanyRole(String companyRole) {
        this.companyRole = companyRole == null ? null : companyRole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workspace_members.view_props
     *
     * @return the value of workspace_members.view_props
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getViewProps() {
        return viewProps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workspace_members.view_props
     *
     * @param viewProps the value for workspace_members.view_props
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setViewProps(String viewProps) {
        this.viewProps = viewProps == null ? null : viewProps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workspace_members.default_props
     *
     * @return the value of workspace_members.default_props
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getDefaultProps() {
        return defaultProps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workspace_members.default_props
     *
     * @param defaultProps the value for workspace_members.default_props
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setDefaultProps(String defaultProps) {
        this.defaultProps = defaultProps == null ? null : defaultProps.trim();
    }
}