package com.server.plane.entity;

import java.util.Date;

public class WorkspaceMembers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workspace_members.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workspace_members.workspace_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String workspaceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workspace_members.member
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private String member;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workspace_members.role
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Integer role;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workspace_members.is_active
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Boolean isActive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workspace_members.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workspace_members.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workspace_members.id
     *
     * @return the value of workspace_members.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workspace_members.id
     *
     * @param id the value for workspace_members.id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workspace_members.workspace_id
     *
     * @return the value of workspace_members.workspace_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getWorkspaceId() {
        return workspaceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workspace_members.workspace_id
     *
     * @param workspaceId the value for workspace_members.workspace_id
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setWorkspaceId(String workspaceId) {
        this.workspaceId = workspaceId == null ? null : workspaceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workspace_members.member
     *
     * @return the value of workspace_members.member
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public String getMember() {
        return member;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workspace_members.member
     *
     * @param member the value for workspace_members.member
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setMember(String member) {
        this.member = member == null ? null : member.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workspace_members.role
     *
     * @return the value of workspace_members.role
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workspace_members.role
     *
     * @param role the value for workspace_members.role
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workspace_members.is_active
     *
     * @return the value of workspace_members.is_active
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Boolean getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workspace_members.is_active
     *
     * @param isActive the value for workspace_members.is_active
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workspace_members.created_at
     *
     * @return the value of workspace_members.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workspace_members.created_at
     *
     * @param createdAt the value for workspace_members.created_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workspace_members.updated_at
     *
     * @return the value of workspace_members.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workspace_members.updated_at
     *
     * @param updatedAt the value for workspace_members.updated_at
     *
     * @mbg.generated Tue Dec 23 23:56:04 ICT 2025
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}